---@meta
-- GENERATED by tools/generate_stubs.py - do not edit by hand.

---@class AreaChart
local AreaChart = {}

--- Get the name property.
---@return string
function AreaChart:getName() end

--- Set the name property.
---@param value string
---@return AreaChart
function AreaChart:setName(value) end

---@class BarChart
local BarChart = {}

---@class BarSet
local BarSet = {}

--- Get the label property.
---@return string
function BarSet:getLabel() end

--- Set the label property.
---@param value string
---@return BarSet
function BarSet:setLabel(value) end

---@class CategoryAxis
local CategoryAxis = {}

---@class Chart
local Chart = {}

--- Get the title property.
---@return string
function Chart:getTitle() end

--- Set the title property.
---@param value string
---@return Chart
function Chart:setTitle(value) end

---@class ChartView
local ChartView = {}

--- Get the enabled property.
---@return boolean
function ChartView:getEnabled() end

--- Set the enabled property.
---@param value boolean
---@return ChartView
function ChartView:setEnabled(value) end

--- Get the enabled property.
---@return boolean
function ChartView:isEnabled() end

--- Get the visible property.
---@return boolean
function ChartView:getVisible() end

--- Set the visible property.
---@param value boolean
---@return ChartView
function ChartView:setVisible(value) end

--- Get the visible property.
---@return boolean
function ChartView:isVisible() end

--- Get the toolTip property.
---@return string
function ChartView:getToolTip() end

--- Set the toolTip property.
---@param value string
---@return ChartView
function ChartView:setToolTip(value) end

--- Get the styleSheet property.
---@return string
function ChartView:getStyleSheet() end

--- Set the styleSheet property.
---@param value string
---@return ChartView
function ChartView:setStyleSheet(value) end

--- Get the chart property.
---@return any
function ChartView:getChart() end

--- Set the chart property.
---@param value any
---@return ChartView
function ChartView:setChart(value) end

---@class LineChart
local LineChart = {}

--- Get the name property.
---@return string
function LineChart:getName() end

--- Set the name property.
---@param value string
---@return LineChart
function LineChart:setName(value) end

---@class ValueAxis
local ValueAxis = {}

--- Get the titleText property.
---@return string
function ValueAxis:getTitleText() end

--- Set the titleText property.
---@param value string
---@return ValueAxis
function ValueAxis:setTitleText(value) end

local chart = {}
chart.AreaChart = AreaChart
chart.BarChart = BarChart
chart.BarSet = BarSet
chart.CategoryAxis = CategoryAxis
chart.Chart = Chart
chart.ChartView = ChartView
chart.LineChart = LineChart
chart.ValueAxis = ValueAxis
return chart
