---@meta
-- GENERATED by tools/generate_stubs.py - do not edit by hand.

---@class AreaChart
local AreaChart = {}

--- Creates a AreaChart.
---@param upper any
---@param lower? any
---@return AreaChart
function AreaChart(upper, lower) end

--- Get the name property.
---@return string
function AreaChart:getName() end

--- Set the name property.
---@param value string
---@return AreaChart
function AreaChart:setName(value) end

---@class BarChart
local BarChart = {}

--- Creates a BarChart.
---@return BarChart
function BarChart() end

--- Qt native re-exposed so it chains like every builder method.
---@param barset any
---@return BarChart
function BarChart:append(barset) end

---@param axis any
---@return BarChart
function BarChart:attachAxis(axis) end

---@class BarSet
local BarSet = {}

--- Creates a BarSet.
---@param title? any
---@return BarSet
function BarSet(title) end

--- Get the label property.
---@return string
function BarSet:getLabel() end

--- Set the label property.
---@param value string
---@return BarSet
function BarSet:setLabel(value) end

--- Accepts a Lua table or Python sequence of numbers.
---@param values any
---@return BarSet
function BarSet:append(values) end

---@class CategoryAxis
local CategoryAxis = {}

--- Creates a CategoryAxis.
---@param categories? any
---@return CategoryAxis
function CategoryAxis(categories) end

--- Accepts a Lua table or Python sequence of category labels.
---@param categories any
---@return CategoryAxis
function CategoryAxis:append(categories) end

---@class Chart
local Chart = {}

--- Creates a Chart.
---@param options? any
---@return Chart
function Chart(options) end

--- Get the title property.
---@return string
function Chart:getTitle() end

--- Set the title property.
---@param value string
---@return Chart
function Chart:setTitle(value) end

---@param axis any
---@param position? any
---@return Chart
function Chart:addAxis(axis, position) end

--- Qt native re-exposed so it chains like every builder method.
---@param series any
---@return Chart
function Chart:addSeries(series) end

---@param animation any
---@return Chart
function Chart:setAnimation(animation) end

---@param position? any
---@return Chart
function Chart:setLegendAlignment(position) end

---@param visible any
---@return Chart
function Chart:setLegendVisibility(visible) end

---@class ChartCanvas
local ChartCanvas = {}

--- Creates a ChartCanvas.
---@param chart? any
---@return ChartCanvas
function ChartCanvas(chart) end

--- Get the enabled property.
---@return boolean
function ChartCanvas:getEnabled() end

--- Set the enabled property.
---@param value boolean
---@return ChartCanvas
function ChartCanvas:setEnabled(value) end

--- Get the enabled property.
---@return boolean
function ChartCanvas:isEnabled() end

--- Get the visible property.
---@return boolean
function ChartCanvas:getVisible() end

--- Set the visible property.
---@param value boolean
---@return ChartCanvas
function ChartCanvas:setVisible(value) end

--- Get the visible property.
---@return boolean
function ChartCanvas:isVisible() end

--- Get the toolTip property.
---@return string
function ChartCanvas:getToolTip() end

--- Set the toolTip property.
---@param value string
---@return ChartCanvas
function ChartCanvas:setToolTip(value) end

--- Get the styleSheet property.
---@return string
function ChartCanvas:getStyleSheet() end

--- Set the styleSheet property.
---@param value string
---@return ChartCanvas
function ChartCanvas:setStyleSheet(value) end

--- Get the chart property.
---@return any
function ChartCanvas:getChart() end

--- Set the chart property.
---@param value any
---@return ChartCanvas
function ChartCanvas:setChart(value) end

function ChartCanvas:close() end

function ChartCanvas:getThemes() end

---@return ChartCanvas
function ChartCanvas:hide() end

---@param colour any
---@return ChartCanvas
function ChartCanvas:setBackgroundColor(colour) end

---@param width any
---@param height any
---@return ChartCanvas
function ChartCanvas:setFixedSize(width, height) end

---@return ChartCanvas
function ChartCanvas:setFocus() end

--- Resizes the height, leaving the width alone.
---@param height integer
---@return ChartCanvas
function ChartCanvas:setHeight(height) end

---@param x any
---@param y any
---@return ChartCanvas
function ChartCanvas:setLocation(x, y) end

--- The space between the widget's edge and its contents.
---@param left integer
---@param top integer
---@param right integer
---@param bottom integer
---@return ChartCanvas
function ChartCanvas:setMargins(left, top, right, bottom) end

--- The largest height the widget may grow to.
---@param height integer
---@return ChartCanvas
function ChartCanvas:setMaxHeight(height) end

--- The largest size the widget may grow to.
---@param width integer
---@param height integer
---@return ChartCanvas
function ChartCanvas:setMaxSize(width, height) end

--- The largest width the widget may grow to.
---@param width integer
---@return ChartCanvas
function ChartCanvas:setMaxWidth(width) end

--- The smallest height the widget may shrink to.
---@param height integer
---@return ChartCanvas
function ChartCanvas:setMinHeight(height) end

--- The smallest size the widget may shrink to.
---@param width integer
---@param height integer
---@return ChartCanvas
function ChartCanvas:setMinSize(width, height) end

--- The smallest width the widget may shrink to.
---@param width integer
---@return ChartCanvas
function ChartCanvas:setMinWidth(width) end

--- One definition, seven policies - not three in some widgets.
---@param horizontal any
---@param vertical any
---@return ChartCanvas
function ChartCanvas:setResizeRule(horizontal, vertical) end

---@param width any
---@param height any
---@return ChartCanvas
function ChartCanvas:setSize(width, height) end

---@param theme any
---@return ChartCanvas
function ChartCanvas:setTheme(theme) end

--- Resizes the width, leaving the height alone.
---@param width integer
---@return ChartCanvas
function ChartCanvas:setWidth(width) end

---@return ChartCanvas
function ChartCanvas:show() end

---@class ChartView
local ChartView = {}

--- Creates a ChartView.
---@param chart? any
---@return ChartView
function ChartView(chart) end

--- Get the enabled property.
---@return boolean
function ChartView:getEnabled() end

--- Set the enabled property.
---@param value boolean
---@return ChartView
function ChartView:setEnabled(value) end

--- Get the enabled property.
---@return boolean
function ChartView:isEnabled() end

--- Get the visible property.
---@return boolean
function ChartView:getVisible() end

--- Set the visible property.
---@param value boolean
---@return ChartView
function ChartView:setVisible(value) end

--- Get the visible property.
---@return boolean
function ChartView:isVisible() end

--- Get the toolTip property.
---@return string
function ChartView:getToolTip() end

--- Set the toolTip property.
---@param value string
---@return ChartView
function ChartView:setToolTip(value) end

--- Get the styleSheet property.
---@return string
function ChartView:getStyleSheet() end

--- Set the styleSheet property.
---@param value string
---@return ChartView
function ChartView:setStyleSheet(value) end

--- Get the chart property.
---@return any
function ChartView:getChart() end

--- Set the chart property.
---@param value any
---@return ChartView
function ChartView:setChart(value) end

function ChartView:close() end

function ChartView:getThemes() end

---@return ChartView
function ChartView:hide() end

---@param colour any
---@return ChartView
function ChartView:setBackgroundColor(colour) end

---@param width any
---@param height any
---@return ChartView
function ChartView:setFixedSize(width, height) end

---@return ChartView
function ChartView:setFocus() end

--- Resizes the height, leaving the width alone.
---@param height integer
---@return ChartView
function ChartView:setHeight(height) end

---@param x any
---@param y any
---@return ChartView
function ChartView:setLocation(x, y) end

--- The space between the widget's edge and its contents.
---@param left integer
---@param top integer
---@param right integer
---@param bottom integer
---@return ChartView
function ChartView:setMargins(left, top, right, bottom) end

--- The largest height the widget may grow to.
---@param height integer
---@return ChartView
function ChartView:setMaxHeight(height) end

--- The largest size the widget may grow to.
---@param width integer
---@param height integer
---@return ChartView
function ChartView:setMaxSize(width, height) end

--- The largest width the widget may grow to.
---@param width integer
---@return ChartView
function ChartView:setMaxWidth(width) end

--- The smallest height the widget may shrink to.
---@param height integer
---@return ChartView
function ChartView:setMinHeight(height) end

--- The smallest size the widget may shrink to.
---@param width integer
---@param height integer
---@return ChartView
function ChartView:setMinSize(width, height) end

--- The smallest width the widget may shrink to.
---@param width integer
---@return ChartView
function ChartView:setMinWidth(width) end

--- One definition, seven policies - not three in some widgets.
---@param horizontal any
---@param vertical any
---@return ChartView
function ChartView:setResizeRule(horizontal, vertical) end

---@param width any
---@param height any
---@return ChartView
function ChartView:setSize(width, height) end

---@param theme any
---@return ChartView
function ChartView:setTheme(theme) end

--- Resizes the width, leaving the height alone.
---@param width integer
---@return ChartView
function ChartView:setWidth(width) end

---@return ChartView
function ChartView:show() end

---@class LineChart
local LineChart = {}

--- Creates a LineChart.
---@return LineChart
function LineChart() end

--- Get the name property.
---@return string
function LineChart:getName() end

--- Set the name property.
---@param value string
---@return LineChart
function LineChart:setName(value) end

--- Qt native re-exposed so it chains like every builder method.
---@param x any
---@param y any
---@return LineChart
function LineChart:append(x, y) end

--- Accepts a Lua table or Python sequence of {x, y} pairs.
---@param points any
---@return LineChart
function LineChart:setData(points) end

---@class ValueAxis
local ValueAxis = {}

--- Creates a ValueAxis.
---@return ValueAxis
function ValueAxis() end

--- Get the titleText property.
---@return string
function ValueAxis:getTitleText() end

--- Set the titleText property.
---@param value string
---@return ValueAxis
function ValueAxis:setTitleText(value) end

--- Qt native re-exposed so it chains like every builder method.
---@param start any
---@param end_ any
---@return ValueAxis
function ValueAxis:setRange(start, end_) end

local chart = {}
chart.AreaChart = AreaChart
chart.BarChart = BarChart
chart.BarSet = BarSet
chart.CategoryAxis = CategoryAxis
chart.Chart = Chart
chart.ChartCanvas = ChartCanvas
chart.ChartView = ChartView
chart.LineChart = LineChart
chart.ValueAxis = ValueAxis
return chart
