---@meta
-- GENERATED by tools/generate_stubs.py - do not edit by hand.

---@class Sqlite3
local Sqlite3 = {}

--- Creates a Sqlite3.
---@param path? any
---@return Sqlite3
function Sqlite3(path) end

--- Copies the whole database to another file.
---@param target string
---@return Sqlite3
function Sqlite3:backup(target) end

--- Starts a transaction.
---@return Sqlite3
function Sqlite3:beginTransaction() end

--- Closes the connection.
---@return Sqlite3
function Sqlite3:close() end

--- Commits the current transaction.
---@return Sqlite3
function Sqlite3:commit() end

--- Creates a table from column names mapped to SQL type definitions.
---@param table_name string
---@param columns table<string, string>
---@param if_not_exists? boolean
---@return Sqlite3
function Sqlite3:createTable(table_name, columns, if_not_exists) end

--- Runs a single SQL statement. Pass params rather than building the SQL by hand.
---@param query string
---@param params? any[]
---@return Sqlite3
function Sqlite3:execute(query, params) end

--- Runs the same statement once per row in data.
---@param query string
---@param data any[][]
---@return Sqlite3
function Sqlite3:executeMany(query, data) end

--- Every remaining row. Pass true to key rows by column name.
---@param as_dict? boolean
---@return any[]
function Sqlite3:fetchAll(as_dict) end

--- The next row only, or nil if there are none left.
---@param as_dict? boolean
---@return any
function Sqlite3:fetchOne(as_dict) end

--- Every table name in the database.
---@return string[]
function Sqlite3:fetchTables() end

--- The column definitions of a table.
---@param table_name string
---@return any[]
function Sqlite3:getTableInfo(table_name) end

--- Inserts a row from column names mapped to values.
---@param table_name string
---@param data table<string, any>
---@param replace? boolean
---@return Sqlite3
function Sqlite3:insert(table_name, data, replace) end

--- Abandons the current transaction.
---@return Sqlite3
function Sqlite3:rollback() end

--- Commits pending changes to disk. Without this, nothing persists.
---@return Sqlite3
function Sqlite3:save() end

--- Whether the table exists.
---@param table_name string
---@return boolean
function Sqlite3:tableExists(table_name) end

--- Compacts the database file.
---@return Sqlite3
function Sqlite3:vacuum() end

local db = {}
db.Sqlite3 = Sqlite3
return db
