---@meta
-- GENERATED by tools/generate_stubs.py - do not edit by hand.

---@class FileSystem
local FileSystem = {}

--- Adds content to the end of the file.
---@param path string
---@param content string
---@param encoding? string
function FileSystem.appendFile(path, content, encoding) end

--- Copies a file.
---@param source string
---@param destination string
function FileSystem.copyFile(source, destination) end

--- Creates an empty file.
---@param path string
function FileSystem.createFile(path) end

--- Creates a folder, including any missing parents.
---@param path string
function FileSystem.createFolder(path) end

--- Deletes a file.
---@param path string
function FileSystem.deleteFile(path) end

--- Whether a file or folder exists.
---@param path string
---@return boolean
function FileSystem.exists(path) end

--- Pretty-prints a JSON string without touching a file.
---@param text string
---@param indent? integer
---@return string
function FileSystem.formatJSON(text, indent) end

--- The folder containing the path.
---@param path string
---@return string
function FileSystem.getDirName(path) end

--- The file extension.
---@param path string
---@return string
function FileSystem.getFileExt(path) end

--- The filename portion of a path.
---@param path string
---@return string
function FileSystem.getFileName(path) end

--- Size in bytes.
---@param path string
---@return integer
function FileSystem.getFileSize(path) end

--- Whether the file has no content.
---@param path string
---@return boolean
function FileSystem.isFileEmpty(path) end

--- Whether the path is a folder.
---@param path string
---@return boolean
function FileSystem.isFolder(path) end

--- Joins path segments with the right separator for the platform.
---@param ... any
---@return string
function FileSystem.joinPaths(...) end

--- The names directly inside a folder.
---@param path string
---@return string[]
function FileSystem.listFolder(path) end

--- Normalises a path.
---@param path string
---@return string
function FileSystem.normalPath(path) end

--- The whole file as a string.
---@param path string
---@param encoding? string
---@return string
function FileSystem.readFile(path, encoding) end

--- The file as a table of lines.
---@param path string
---@param encoding? string
---@return string[]
function FileSystem.readFileLines(path, encoding) end

--- Reads a JSON file and returns it as a lua table.
---@param path string
---@return table
function FileSystem.readJSON(path) end

--- Renames or moves a file.
---@param path string
---@param new_path string
function FileSystem.renameFile(path, new_path) end

--- Walks a folder recursively.
---@param path string
---@param show_hidden? boolean
---@return string[]
function FileSystem.walkDir(path, show_hidden) end

--- Writes content, replacing whatever was there.
---@param path string
---@param content string
---@param encoding? string
function FileSystem.writeFile(path, content, encoding) end

--- Writes a lua table as JSON.
---@param path string
---@param data table
---@param indent? integer
function FileSystem.writeJSON(path, data, indent) end

local fs = {}
fs.FileSystem = FileSystem
return fs
