---@meta
-- GENERATED by tools/generate_stubs.py - do not edit by hand.

---@class Resources
local Resources = {}

--- The full path to a file in the project's images folder.
---@param name string
---@return string
function Resources.images(name) end

--- The full path to a file in the project's misc folder.
---@param name string
---@return string
function Resources.misc(name) end

--- Resolves a named route declared in app.json.
---@param key string
---@return string
function Resources.route(key) end

--- The full path to a file in the project's scripts folder.
---@param name string
---@return string
function Resources.scripts(name) end

local res = {}
res.Resources = Resources
return res
