---@meta
-- GENERATED by tools/generate_stubs.py - do not edit by hand.

---@class Expr
local Expr = {}

--- Arithmetic only. Never exposes builtins.eval to Lua.
---@param expression any
function Expr.evalExpression(expression) end

---@class ProjectBuilder
local ProjectBuilder = {}

--- Creates a ProjectBuilder.
---@param project_path any
---@param options? any
---@return ProjectBuilder
function ProjectBuilder(project_path, options) end

--- Starts the build.
---@return ProjectBuilder
function ProjectBuilder:build() end

--- Every line the build has produced so far.
---@return string[]
function ProjectBuilder:getOutput() end

--- Path to the built executable, once the build has finished.
---@return string
function ProjectBuilder:getOutputPath() end

--- The project folder this builder was created for.
---@return string
function ProjectBuilder:getPath() end

--- Whether the finished build succeeded.
---@return boolean
function ProjectBuilder:isSuccess() end

--- Runs if the build fails with an error.
---@param handler fun(message: string)
---@return ProjectBuilder
function ProjectBuilder:setOnBuildError(handler) end

--- Runs when the build finishes, successfully or not.
---@param handler fun(success: boolean, output_path: string)
---@return ProjectBuilder
function ProjectBuilder:setOnBuildFinished(handler) end

--- Runs for each line the build writes. Use it to drive a console view.
---@param handler fun(line: string)
---@return ProjectBuilder
function ProjectBuilder:setOnBuildOutput(handler) end

--- Runs once the build has started.
---@param handler fun()
---@return ProjectBuilder
function ProjectBuilder:setOnBuildStarted(handler) end

--- Stops a build in progress.
---@return ProjectBuilder
function ProjectBuilder:stop() end

---@class ProjectRunner
local ProjectRunner = {}

--- Creates a ProjectRunner.
---@param project_path any
---@return ProjectRunner
function ProjectRunner(project_path) end

--- The engine this project will run on: "1.0" or "2.0".
---@return string
function ProjectRunner:getApiVersion() end

--- The project folder this runner was created for.
---@return string
function ProjectRunner:getPath() end

--- Whether the project is currently running.
---@return boolean
function ProjectRunner:isRunning() end

--- Starts the project.
---@return ProjectRunner
function ProjectRunner:run() end

--- Runs when the project exits, however it exits.
---@param handler fun()
---@return ProjectRunner
function ProjectRunner:setOnProcessFinished(handler) end

--- Runs when the project writes to stdout or stderr.
---@param handler fun(output: string)
---@return ProjectRunner
function ProjectRunner:setOnProcessReadyRead(handler) end

--- Runs once the child process has started.
---@param handler fun()
---@return ProjectRunner
function ProjectRunner:setOnProcessStarted(handler) end

--- Stops the project.
---@return ProjectRunner
function ProjectRunner:stop() end

---@class Signal
local Signal = {}

--- Creates a Signal.
---@return Signal
function Signal() end

--- Fires the signal -- safe to call across threads, unlike calling a handler directly.
---@return Signal
function Signal:relay() end

---@param handler any
---@return Signal
function Signal:setOnSignal(handler) end

---@class System
local System = {}

--- Turns a byte count into a readable size such as 1.4 MB.
---@param size integer
---@return string
function System.bytesToReadableSize(size) end

--- Looks up an emoji by name.
---@param name string
---@return string
function System.emoji(name) end

--- Runs an external command and returns its output. Bounded at 30 seconds.
---@param cmd string
---@return string
function System.execute(cmd) end

--- Quits the application.
---@param code? integer
function System.exit(code) end

--- Decodes a base64 string.
---@param text string
---@return string
function System.fromBase64(text) end

--- How many CPU cores are available.
---@return integer
function System.getCPUCount() end

--- The text currently on the clipboard.
---@return string
function System.getClipboardText() end

--- The operating system name.
---@return string
function System.getOSName() end

--- The operating system version.
---@return string
function System.getOSVersion() end

--- The platform identifier.
---@return string
function System.getPlatformName() end

--- The CPU model name.
---@return string
function System.getProcessorName() end

--- A well-known folder such as desktop, documents, downloads or temp.
---@param name string
---@return string
function System.getStandardPath(name) end

--- Hashes a string: md5, sha1, sha224, sha256, sha384 or sha512.
---@param kind string
---@param text string
---@return string
function System.makeHash(kind, text) end

--- Picks one item from a table at random.
---@param items any[]
---@return any
function System.randomChoice(items) end

--- Puts text on the clipboard.
---@param text string
function System.setClipboardText(text) end

--- Pauses for a number of seconds. Blocks the interface -- prefer sys.Thread.
---@param seconds number
function System.sleep(seconds) end

--- Splits a string into a table.
---@param text string
---@param sep? string
---@return string[]
function System.splitString(text, sep) end

--- Encodes a string as base64.
---@param text string
---@return string
function System.toBase64(text) end

---@class Thread
local Thread = {}

--- Creates a Thread.
---@return Thread
function Thread() end

function Thread:isRunning() end

---@param handler any
---@return Thread
function Thread:setOnThreadRun(handler) end

--- Pauses the calling thread for `seconds` -- QThread.sleep is a static method in Qt; exposed here as an instance method so Lua's `thread:sleep(2)` colon syntax works.
---@param seconds any
---@return Thread
function Thread:sleep(seconds) end

---@return Thread
function Thread:start() end

---@return Thread
function Thread:stop() end

---@param msecs? any
---@return Thread
function Thread:wait(msecs) end

---@class Timer
local Timer = {}

--- Get the timer's interval, in milliseconds.
---@return integer
function Timer:getInterval() end

--- Set the timer's interval, in milliseconds.
---@param value integer
---@return Timer
function Timer:setInterval(value) end

--- Get the single_shot property.
---@return boolean
function Timer:getSingleShot() end

--- Set the single_shot property.
---@param value boolean
---@return Timer
function Timer:setSingleShot(value) end

--- Get the single_shot property.
---@return boolean
function Timer:isSingleShot() end

--- Fired every time the timer fires.
---@param handler fun(widget: Timer)
---@return Timer
function Timer:setOnTimeout(handler) end

function Timer:isActive() end

--- Fire `callback` once after `msec` milliseconds. The callback is guarded like every other Lua-attached handler -- 1.x's static `singleShot` connected the raw Lua function straight to `QTimer.singleShot`, so an error inside it would have escaped uncaught into the Qt event loop.
---@param msec any
---@param callback any
function Timer.singleShot(msec, callback) end

--- Qt native re-exposed so Lua's `timer:start()` colon syntax works. Accepts an optional one-shot interval override, matching `QTimer.start(msec)`'s overload, on top of 1.x's no-argument form.
---@param msec? any
---@return Timer
function Timer:start(msec) end

---@return Timer
function Timer:stop() end

local sys = {}
sys.Expr = Expr
sys.ProjectBuilder = ProjectBuilder
sys.ProjectRunner = ProjectRunner
sys.Signal = Signal
sys.System = System
sys.Thread = Thread
sys.Timer = Timer
return sys
