---@meta
-- GENERATED by tools/generate_stubs.py - do not edit by hand.

---@class Accordion
local Accordion = {}

--- Get the enabled property.
---@return boolean
function Accordion:getEnabled() end

--- Set the enabled property.
---@param value boolean
---@return Accordion
function Accordion:setEnabled(value) end

--- Get the enabled property.
---@return boolean
function Accordion:isEnabled() end

--- Get the visible property.
---@return boolean
function Accordion:getVisible() end

--- Set the visible property.
---@param value boolean
---@return Accordion
function Accordion:setVisible(value) end

--- Get the visible property.
---@return boolean
function Accordion:isVisible() end

--- Get the toolTip property.
---@return string
function Accordion:getToolTip() end

--- Set the toolTip property.
---@param value string
---@return Accordion
function Accordion:setToolTip(value) end

--- Get the styleSheet property.
---@return string
function Accordion:getStyleSheet() end

--- Set the styleSheet property.
---@param value string
---@return Accordion
function Accordion:setStyleSheet(value) end

--- Get the currentIndex property.
---@return integer
function Accordion:getCurrentIndex() end

--- Set the currentIndex property.
---@param value integer
---@return Accordion
function Accordion:setCurrentIndex(value) end

---@class AdvancedSlider
local AdvancedSlider = {}

--- Get the enabled property.
---@return boolean
function AdvancedSlider:getEnabled() end

--- Set the enabled property.
---@param value boolean
---@return AdvancedSlider
function AdvancedSlider:setEnabled(value) end

--- Get the enabled property.
---@return boolean
function AdvancedSlider:isEnabled() end

--- Get the visible property.
---@return boolean
function AdvancedSlider:getVisible() end

--- Set the visible property.
---@param value boolean
---@return AdvancedSlider
function AdvancedSlider:setVisible(value) end

--- Get the visible property.
---@return boolean
function AdvancedSlider:isVisible() end

--- Get the toolTip property.
---@return string
function AdvancedSlider:getToolTip() end

--- Set the toolTip property.
---@param value string
---@return AdvancedSlider
function AdvancedSlider:setToolTip(value) end

--- Get the styleSheet property.
---@return string
function AdvancedSlider:getStyleSheet() end

--- Set the styleSheet property.
---@param value string
---@return AdvancedSlider
function AdvancedSlider:setStyleSheet(value) end

--- Attach a handler for onValueChanged.
---@param handler fun(widget: AdvancedSlider)
---@return AdvancedSlider
function AdvancedSlider:setOnValueChanged(handler) end

---@class AutoComplete
local AutoComplete = {}

---@class Button
local Button = {}

--- Get the enabled property.
---@return boolean
function Button:getEnabled() end

--- Set the enabled property.
---@param value boolean
---@return Button
function Button:setEnabled(value) end

--- Get the enabled property.
---@return boolean
function Button:isEnabled() end

--- Get the visible property.
---@return boolean
function Button:getVisible() end

--- Set the visible property.
---@param value boolean
---@return Button
function Button:setVisible(value) end

--- Get the visible property.
---@return boolean
function Button:isVisible() end

--- Get the toolTip property.
---@return string
function Button:getToolTip() end

--- Set the toolTip property.
---@param value string
---@return Button
function Button:setToolTip(value) end

--- Get the styleSheet property.
---@return string
function Button:getStyleSheet() end

--- Set the styleSheet property.
---@param value string
---@return Button
function Button:setStyleSheet(value) end

--- Get the button's caption.
---@return string
function Button:getText() end

--- Set the button's caption.
---@param value string
---@return Button
function Button:setText(value) end

--- Get the icon property.
---@return any
function Button:getIcon() end

--- Set the icon property.
---@param value any
---@return Button
function Button:setIcon(value) end

--- Get the flat property.
---@return boolean
function Button:getFlat() end

--- Set the flat property.
---@param value boolean
---@return Button
function Button:setFlat(value) end

--- Get the flat property.
---@return boolean
function Button:isFlat() end

--- Get the checkable property.
---@return boolean
function Button:getCheckable() end

--- Set the checkable property.
---@param value boolean
---@return Button
function Button:setCheckable(value) end

--- Get the checkable property.
---@return boolean
function Button:isCheckable() end

--- Get the checked property.
---@return boolean
function Button:getChecked() end

--- Set the checked property.
---@param value boolean
---@return Button
function Button:setChecked(value) end

--- Get the checked property.
---@return boolean
function Button:isChecked() end

--- Fired when clicked.
---@param handler fun(widget: Button)
---@return Button
function Button:setOnClick(handler) end

---@class ButtonGroup
local ButtonGroup = {}

--- Get the exclusive property.
---@return boolean
function ButtonGroup:getExclusive() end

--- Set the exclusive property.
---@param value boolean
---@return ButtonGroup
function ButtonGroup:setExclusive(value) end

--- Get the exclusive property.
---@return boolean
function ButtonGroup:isExclusive() end

--- Attach a handler for onClick.
---@param handler fun(widget: ButtonGroup)
---@return ButtonGroup
function ButtonGroup:setOnClick(handler) end

---@class Calendar
local Calendar = {}

--- Get the enabled property.
---@return boolean
function Calendar:getEnabled() end

--- Set the enabled property.
---@param value boolean
---@return Calendar
function Calendar:setEnabled(value) end

--- Get the enabled property.
---@return boolean
function Calendar:isEnabled() end

--- Get the visible property.
---@return boolean
function Calendar:getVisible() end

--- Set the visible property.
---@param value boolean
---@return Calendar
function Calendar:setVisible(value) end

--- Get the visible property.
---@return boolean
function Calendar:isVisible() end

--- Get the toolTip property.
---@return string
function Calendar:getToolTip() end

--- Set the toolTip property.
---@param value string
---@return Calendar
function Calendar:setToolTip(value) end

--- Get the styleSheet property.
---@return string
function Calendar:getStyleSheet() end

--- Set the styleSheet property.
---@param value string
---@return Calendar
function Calendar:setStyleSheet(value) end

---@class CheckBox
local CheckBox = {}

--- Get the enabled property.
---@return boolean
function CheckBox:getEnabled() end

--- Set the enabled property.
---@param value boolean
---@return CheckBox
function CheckBox:setEnabled(value) end

--- Get the enabled property.
---@return boolean
function CheckBox:isEnabled() end

--- Get the visible property.
---@return boolean
function CheckBox:getVisible() end

--- Set the visible property.
---@param value boolean
---@return CheckBox
function CheckBox:setVisible(value) end

--- Get the visible property.
---@return boolean
function CheckBox:isVisible() end

--- Get the toolTip property.
---@return string
function CheckBox:getToolTip() end

--- Set the toolTip property.
---@param value string
---@return CheckBox
function CheckBox:setToolTip(value) end

--- Get the styleSheet property.
---@return string
function CheckBox:getStyleSheet() end

--- Set the styleSheet property.
---@param value string
---@return CheckBox
function CheckBox:setStyleSheet(value) end

--- Get the text property.
---@return string
function CheckBox:getText() end

--- Set the text property.
---@param value string
---@return CheckBox
function CheckBox:setText(value) end

--- Get the checked property.
---@return boolean
function CheckBox:getChecked() end

--- Set the checked property.
---@param value boolean
---@return CheckBox
function CheckBox:setChecked(value) end

--- Get the checked property.
---@return boolean
function CheckBox:isChecked() end

--- Attach a handler for onCheck.
---@param handler fun(widget: CheckBox)
---@return CheckBox
function CheckBox:setOnCheck(handler) end

---@class ComboBox
local ComboBox = {}

--- Get the enabled property.
---@return boolean
function ComboBox:getEnabled() end

--- Set the enabled property.
---@param value boolean
---@return ComboBox
function ComboBox:setEnabled(value) end

--- Get the enabled property.
---@return boolean
function ComboBox:isEnabled() end

--- Get the visible property.
---@return boolean
function ComboBox:getVisible() end

--- Set the visible property.
---@param value boolean
---@return ComboBox
function ComboBox:setVisible(value) end

--- Get the visible property.
---@return boolean
function ComboBox:isVisible() end

--- Get the toolTip property.
---@return string
function ComboBox:getToolTip() end

--- Set the toolTip property.
---@param value string
---@return ComboBox
function ComboBox:setToolTip(value) end

--- Get the styleSheet property.
---@return string
function ComboBox:getStyleSheet() end

--- Set the styleSheet property.
---@param value string
---@return ComboBox
function ComboBox:setStyleSheet(value) end

--- Get the editable property.
---@return boolean
function ComboBox:getEditable() end

--- Set the editable property.
---@param value boolean
---@return ComboBox
function ComboBox:setEditable(value) end

--- Get the editable property.
---@return boolean
function ComboBox:isEditable() end

--- Attach a handler for onItemSelect.
---@param handler fun(widget: ComboBox)
---@return ComboBox
function ComboBox:setOnItemSelect(handler) end

---@class CommandButton
local CommandButton = {}

--- Get the enabled property.
---@return boolean
function CommandButton:getEnabled() end

--- Set the enabled property.
---@param value boolean
---@return CommandButton
function CommandButton:setEnabled(value) end

--- Get the enabled property.
---@return boolean
function CommandButton:isEnabled() end

--- Get the visible property.
---@return boolean
function CommandButton:getVisible() end

--- Set the visible property.
---@param value boolean
---@return CommandButton
function CommandButton:setVisible(value) end

--- Get the visible property.
---@return boolean
function CommandButton:isVisible() end

--- Get the toolTip property.
---@return string
function CommandButton:getToolTip() end

--- Set the toolTip property.
---@param value string
---@return CommandButton
function CommandButton:setToolTip(value) end

--- Get the styleSheet property.
---@return string
function CommandButton:getStyleSheet() end

--- Set the styleSheet property.
---@param value string
---@return CommandButton
function CommandButton:setStyleSheet(value) end

--- Get the text property.
---@return string
function CommandButton:getText() end

--- Set the text property.
---@param value string
---@return CommandButton
function CommandButton:setText(value) end

--- Get the description property.
---@return string
function CommandButton:getDescription() end

--- Set the description property.
---@param value string
---@return CommandButton
function CommandButton:setDescription(value) end

--- Get the icon property.
---@return any
function CommandButton:getIcon() end

--- Set the icon property.
---@param value any
---@return CommandButton
function CommandButton:setIcon(value) end

--- Attach a handler for onClick.
---@param handler fun(widget: CommandButton)
---@return CommandButton
function CommandButton:setOnClick(handler) end

---@class Container
local Container = {}

--- Get the enabled property.
---@return boolean
function Container:getEnabled() end

--- Set the enabled property.
---@param value boolean
---@return Container
function Container:setEnabled(value) end

--- Get the enabled property.
---@return boolean
function Container:isEnabled() end

--- Get the visible property.
---@return boolean
function Container:getVisible() end

--- Set the visible property.
---@param value boolean
---@return Container
function Container:setVisible(value) end

--- Get the visible property.
---@return boolean
function Container:isVisible() end

--- Get the toolTip property.
---@return string
function Container:getToolTip() end

--- Set the toolTip property.
---@param value string
---@return Container
function Container:setToolTip(value) end

--- Get the styleSheet property.
---@return string
function Container:getStyleSheet() end

--- Set the styleSheet property.
---@param value string
---@return Container
function Container:setStyleSheet(value) end

--- Get the layout property.
---@return any
function Container:getLayout() end

--- Set the layout property.
---@param value any
---@return Container
function Container:setLayout(value) end

---@class DatePicker
local DatePicker = {}

--- Get the enabled property.
---@return boolean
function DatePicker:getEnabled() end

--- Set the enabled property.
---@param value boolean
---@return DatePicker
function DatePicker:setEnabled(value) end

--- Get the enabled property.
---@return boolean
function DatePicker:isEnabled() end

--- Get the visible property.
---@return boolean
function DatePicker:getVisible() end

--- Set the visible property.
---@param value boolean
---@return DatePicker
function DatePicker:setVisible(value) end

--- Get the visible property.
---@return boolean
function DatePicker:isVisible() end

--- Get the toolTip property.
---@return string
function DatePicker:getToolTip() end

--- Set the toolTip property.
---@param value string
---@return DatePicker
function DatePicker:setToolTip(value) end

--- Get the styleSheet property.
---@return string
function DatePicker:getStyleSheet() end

--- Set the styleSheet property.
---@param value string
---@return DatePicker
function DatePicker:setStyleSheet(value) end

---@class Dialogs
local Dialogs = {}

---@class Dock
local Dock = {}

--- Get the enabled property.
---@return boolean
function Dock:getEnabled() end

--- Set the enabled property.
---@param value boolean
---@return Dock
function Dock:setEnabled(value) end

--- Get the enabled property.
---@return boolean
function Dock:isEnabled() end

--- Get the visible property.
---@return boolean
function Dock:getVisible() end

--- Set the visible property.
---@param value boolean
---@return Dock
function Dock:setVisible(value) end

--- Get the visible property.
---@return boolean
function Dock:isVisible() end

--- Get the toolTip property.
---@return string
function Dock:getToolTip() end

--- Set the toolTip property.
---@param value string
---@return Dock
function Dock:setToolTip(value) end

--- Get the styleSheet property.
---@return string
function Dock:getStyleSheet() end

--- Set the styleSheet property.
---@param value string
---@return Dock
function Dock:setStyleSheet(value) end

--- Get the title property.
---@return string
function Dock:getTitle() end

--- Set the title property.
---@param value string
---@return Dock
function Dock:setTitle(value) end

--- Get the icon property.
---@return any
function Dock:getIcon() end

--- Set the icon property.
---@param value any
---@return Dock
function Dock:setIcon(value) end

--- Get the floating property.
---@return boolean
function Dock:getFloating() end

--- Set the floating property.
---@param value boolean
---@return Dock
function Dock:setFloating(value) end

--- Get the floating property.
---@return boolean
function Dock:isFloating() end

--- Attach a handler for onLocationChange.
---@param handler fun(widget: Dock)
---@return Dock
function Dock:setOnLocationChange(handler) end

--- Attach a handler for onVisibilityChange.
---@param handler fun(widget: Dock)
---@return Dock
function Dock:setOnVisibilityChange(handler) end

---@class Dockable
local Dockable = {}

--- Get the enabled property.
---@return boolean
function Dockable:getEnabled() end

--- Set the enabled property.
---@param value boolean
---@return Dockable
function Dockable:setEnabled(value) end

--- Get the enabled property.
---@return boolean
function Dockable:isEnabled() end

--- Get the visible property.
---@return boolean
function Dockable:getVisible() end

--- Set the visible property.
---@param value boolean
---@return Dockable
function Dockable:setVisible(value) end

--- Get the visible property.
---@return boolean
function Dockable:isVisible() end

--- Get the toolTip property.
---@return string
function Dockable:getToolTip() end

--- Set the toolTip property.
---@param value string
---@return Dockable
function Dockable:setToolTip(value) end

--- Get the styleSheet property.
---@return string
function Dockable:getStyleSheet() end

--- Set the styleSheet property.
---@param value string
---@return Dockable
function Dockable:setStyleSheet(value) end

--- Get the title property.
---@return string
function Dockable:getTitle() end

--- Set the title property.
---@param value string
---@return Dockable
function Dockable:setTitle(value) end

--- Get the icon property.
---@return any
function Dockable:getIcon() end

--- Set the icon property.
---@param value any
---@return Dockable
function Dockable:setIcon(value) end

--- Get the floating property.
---@return boolean
function Dockable:getFloating() end

--- Set the floating property.
---@param value boolean
---@return Dockable
function Dockable:setFloating(value) end

--- Get the floating property.
---@return boolean
function Dockable:isFloating() end

--- Attach a handler for onLocationChange.
---@param handler fun(widget: Dockable)
---@return Dockable
function Dockable:setOnLocationChange(handler) end

--- Attach a handler for onVisibilityChange.
---@param handler fun(widget: Dockable)
---@return Dockable
function Dockable:setOnVisibilityChange(handler) end

---@class DoubleSpinner
local DoubleSpinner = {}

--- Get the enabled property.
---@return boolean
function DoubleSpinner:getEnabled() end

--- Set the enabled property.
---@param value boolean
---@return DoubleSpinner
function DoubleSpinner:setEnabled(value) end

--- Get the enabled property.
---@return boolean
function DoubleSpinner:isEnabled() end

--- Get the visible property.
---@return boolean
function DoubleSpinner:getVisible() end

--- Set the visible property.
---@param value boolean
---@return DoubleSpinner
function DoubleSpinner:setVisible(value) end

--- Get the visible property.
---@return boolean
function DoubleSpinner:isVisible() end

--- Get the toolTip property.
---@return string
function DoubleSpinner:getToolTip() end

--- Set the toolTip property.
---@param value string
---@return DoubleSpinner
function DoubleSpinner:setToolTip(value) end

--- Get the styleSheet property.
---@return string
function DoubleSpinner:getStyleSheet() end

--- Set the styleSheet property.
---@param value string
---@return DoubleSpinner
function DoubleSpinner:setStyleSheet(value) end

--- Get the value property.
---@return number
function DoubleSpinner:getValue() end

--- Set the value property.
---@param value number
---@return DoubleSpinner
function DoubleSpinner:setValue(value) end

--- Get the prefix property.
---@return string
function DoubleSpinner:getPrefix() end

--- Set the prefix property.
---@param value string
---@return DoubleSpinner
function DoubleSpinner:setPrefix(value) end

--- Get the suffix property.
---@return string
function DoubleSpinner:getSuffix() end

--- Set the suffix property.
---@param value string
---@return DoubleSpinner
function DoubleSpinner:setSuffix(value) end

--- Attach a handler for onValueChange.
---@param handler fun(widget: DoubleSpinner)
---@return DoubleSpinner
function DoubleSpinner:setOnValueChange(handler) end

---@class DropMenu
local DropMenu = {}

--- Get the enabled property.
---@return boolean
function DropMenu:getEnabled() end

--- Set the enabled property.
---@param value boolean
---@return DropMenu
function DropMenu:setEnabled(value) end

--- Get the enabled property.
---@return boolean
function DropMenu:isEnabled() end

--- Get the visible property.
---@return boolean
function DropMenu:getVisible() end

--- Set the visible property.
---@param value boolean
---@return DropMenu
function DropMenu:setVisible(value) end

--- Get the visible property.
---@return boolean
function DropMenu:isVisible() end

--- Get the toolTip property.
---@return string
function DropMenu:getToolTip() end

--- Set the toolTip property.
---@param value string
---@return DropMenu
function DropMenu:setToolTip(value) end

--- Get the styleSheet property.
---@return string
function DropMenu:getStyleSheet() end

--- Set the styleSheet property.
---@param value string
---@return DropMenu
function DropMenu:setStyleSheet(value) end

--- Get the title property.
---@return string
function DropMenu:getTitle() end

--- Set the title property.
---@param value string
---@return DropMenu
function DropMenu:setTitle(value) end

--- Get the icon property.
---@return any
function DropMenu:getIcon() end

--- Set the icon property.
---@param value any
---@return DropMenu
function DropMenu:setIcon(value) end

--- Attach a handler for onClick.
---@param handler fun(widget: DropMenu)
---@return DropMenu
function DropMenu:setOnClick(handler) end

---@class DropShadow
local DropShadow = {}

--- Get the shadow's blur radius, in pixels.
---@return number
function DropShadow:getBlurRadius() end

--- Set the shadow's blur radius, in pixels.
---@param value number
---@return DropShadow
function DropShadow:setBlurRadius(value) end

--- Get the color property.
---@return any
function DropShadow:getColor() end

--- Set the color property.
---@param value any
---@return DropShadow
function DropShadow:setColor(value) end

--- Get the offsetX property.
---@return number
function DropShadow:getOffsetX() end

--- Set the offsetX property.
---@param value number
---@return DropShadow
function DropShadow:setOffsetX(value) end

--- Get the offsetY property.
---@return number
function DropShadow:getOffsetY() end

--- Set the offsetY property.
---@param value number
---@return DropShadow
function DropShadow:setOffsetY(value) end

---@class FontComboBox
local FontComboBox = {}

--- Get the enabled property.
---@return boolean
function FontComboBox:getEnabled() end

--- Set the enabled property.
---@param value boolean
---@return FontComboBox
function FontComboBox:setEnabled(value) end

--- Get the enabled property.
---@return boolean
function FontComboBox:isEnabled() end

--- Get the visible property.
---@return boolean
function FontComboBox:getVisible() end

--- Set the visible property.
---@param value boolean
---@return FontComboBox
function FontComboBox:setVisible(value) end

--- Get the visible property.
---@return boolean
function FontComboBox:isVisible() end

--- Get the toolTip property.
---@return string
function FontComboBox:getToolTip() end

--- Set the toolTip property.
---@param value string
---@return FontComboBox
function FontComboBox:setToolTip(value) end

--- Get the styleSheet property.
---@return string
function FontComboBox:getStyleSheet() end

--- Set the styleSheet property.
---@param value string
---@return FontComboBox
function FontComboBox:setStyleSheet(value) end

--- Get the currentFont property.
---@return any
function FontComboBox:getCurrentFont() end

--- Set the currentFont property.
---@param value any
---@return FontComboBox
function FontComboBox:setCurrentFont(value) end

---@class FormLayout
local FormLayout = {}

--- Get the spacing property.
---@return integer
function FormLayout:getSpacing() end

--- Set the spacing property.
---@param value integer
---@return FormLayout
function FormLayout:setSpacing(value) end

---@class GifPlayer
local GifPlayer = {}

--- Get the enabled property.
---@return boolean
function GifPlayer:getEnabled() end

--- Set the enabled property.
---@param value boolean
---@return GifPlayer
function GifPlayer:setEnabled(value) end

--- Get the enabled property.
---@return boolean
function GifPlayer:isEnabled() end

--- Get the visible property.
---@return boolean
function GifPlayer:getVisible() end

--- Set the visible property.
---@param value boolean
---@return GifPlayer
function GifPlayer:setVisible(value) end

--- Get the visible property.
---@return boolean
function GifPlayer:isVisible() end

--- Get the toolTip property.
---@return string
function GifPlayer:getToolTip() end

--- Set the toolTip property.
---@param value string
---@return GifPlayer
function GifPlayer:setToolTip(value) end

--- Get the styleSheet property.
---@return string
function GifPlayer:getStyleSheet() end

--- Set the styleSheet property.
---@param value string
---@return GifPlayer
function GifPlayer:setStyleSheet(value) end

---@class GridLayout
local GridLayout = {}

--- Get the spacing property.
---@return integer
function GridLayout:getSpacing() end

--- Set the spacing property.
---@param value integer
---@return GridLayout
function GridLayout:setSpacing(value) end

---@class GroupBox
local GroupBox = {}

--- Get the enabled property.
---@return boolean
function GroupBox:getEnabled() end

--- Set the enabled property.
---@param value boolean
---@return GroupBox
function GroupBox:setEnabled(value) end

--- Get the enabled property.
---@return boolean
function GroupBox:isEnabled() end

--- Get the visible property.
---@return boolean
function GroupBox:getVisible() end

--- Set the visible property.
---@param value boolean
---@return GroupBox
function GroupBox:setVisible(value) end

--- Get the visible property.
---@return boolean
function GroupBox:isVisible() end

--- Get the toolTip property.
---@return string
function GroupBox:getToolTip() end

--- Set the toolTip property.
---@param value string
---@return GroupBox
function GroupBox:setToolTip(value) end

--- Get the styleSheet property.
---@return string
function GroupBox:getStyleSheet() end

--- Set the styleSheet property.
---@param value string
---@return GroupBox
function GroupBox:setStyleSheet(value) end

--- Get the title property.
---@return string
function GroupBox:getTitle() end

--- Set the title property.
---@param value string
---@return GroupBox
function GroupBox:setTitle(value) end

--- Get the checkable property.
---@return boolean
function GroupBox:getCheckable() end

--- Set the checkable property.
---@param value boolean
---@return GroupBox
function GroupBox:setCheckable(value) end

--- Get the checkable property.
---@return boolean
function GroupBox:isCheckable() end

--- Get the checked property.
---@return boolean
function GroupBox:getChecked() end

--- Set the checked property.
---@param value boolean
---@return GroupBox
function GroupBox:setChecked(value) end

--- Get the checked property.
---@return boolean
function GroupBox:isChecked() end

--- Get the flat property.
---@return boolean
function GroupBox:getFlat() end

--- Set the flat property.
---@param value boolean
---@return GroupBox
function GroupBox:setFlat(value) end

--- Get the flat property.
---@return boolean
function GroupBox:isFlat() end

--- Get the layout property.
---@return any
function GroupBox:getLayout() end

--- Set the layout property.
---@param value any
---@return GroupBox
function GroupBox:setLayout(value) end

---@class HLayout
local HLayout = {}

--- Get the spacing property.
---@return integer
function HLayout:getSpacing() end

--- Set the spacing property.
---@param value integer
---@return HLayout
function HLayout:setSpacing(value) end

---@class HLine
local HLine = {}

--- Get the enabled property.
---@return boolean
function HLine:getEnabled() end

--- Set the enabled property.
---@param value boolean
---@return HLine
function HLine:setEnabled(value) end

--- Get the enabled property.
---@return boolean
function HLine:isEnabled() end

--- Get the visible property.
---@return boolean
function HLine:getVisible() end

--- Set the visible property.
---@param value boolean
---@return HLine
function HLine:setVisible(value) end

--- Get the visible property.
---@return boolean
function HLine:isVisible() end

--- Get the toolTip property.
---@return string
function HLine:getToolTip() end

--- Set the toolTip property.
---@param value string
---@return HLine
function HLine:setToolTip(value) end

--- Get the styleSheet property.
---@return string
function HLine:getStyleSheet() end

--- Set the styleSheet property.
---@param value string
---@return HLine
function HLine:setStyleSheet(value) end

---@class Image
local Image = {}

--- Get the enabled property.
---@return boolean
function Image:getEnabled() end

--- Set the enabled property.
---@param value boolean
---@return Image
function Image:setEnabled(value) end

--- Get the enabled property.
---@return boolean
function Image:isEnabled() end

--- Get the visible property.
---@return boolean
function Image:getVisible() end

--- Set the visible property.
---@param value boolean
---@return Image
function Image:setVisible(value) end

--- Get the visible property.
---@return boolean
function Image:isVisible() end

--- Get the toolTip property.
---@return string
function Image:getToolTip() end

--- Set the toolTip property.
---@param value string
---@return Image
function Image:setToolTip(value) end

--- Get the styleSheet property.
---@return string
function Image:getStyleSheet() end

--- Set the styleSheet property.
---@param value string
---@return Image
function Image:setStyleSheet(value) end

---@class KeyboardShortcut
local KeyboardShortcut = {}

--- Get the enabled property.
---@return boolean
function KeyboardShortcut:getEnabled() end

--- Set the enabled property.
---@param value boolean
---@return KeyboardShortcut
function KeyboardShortcut:setEnabled(value) end

--- Get the enabled property.
---@return boolean
function KeyboardShortcut:isEnabled() end

--- Get the autoRepeat property.
---@return boolean
function KeyboardShortcut:getAutoRepeat() end

--- Set the autoRepeat property.
---@param value boolean
---@return KeyboardShortcut
function KeyboardShortcut:setAutoRepeat(value) end

--- Get the autoRepeat property.
---@return boolean
function KeyboardShortcut:isAutoRepeat() end

--- Fired when the key sequence is pressed.
---@param handler fun(widget: KeyboardShortcut)
---@return KeyboardShortcut
function KeyboardShortcut:setOnPress(handler) end

---@class Knob
local Knob = {}

--- Get the enabled property.
---@return boolean
function Knob:getEnabled() end

--- Set the enabled property.
---@param value boolean
---@return Knob
function Knob:setEnabled(value) end

--- Get the enabled property.
---@return boolean
function Knob:isEnabled() end

--- Get the visible property.
---@return boolean
function Knob:getVisible() end

--- Set the visible property.
---@param value boolean
---@return Knob
function Knob:setVisible(value) end

--- Get the visible property.
---@return boolean
function Knob:isVisible() end

--- Get the toolTip property.
---@return string
function Knob:getToolTip() end

--- Set the toolTip property.
---@param value string
---@return Knob
function Knob:setToolTip(value) end

--- Get the styleSheet property.
---@return string
function Knob:getStyleSheet() end

--- Set the styleSheet property.
---@param value string
---@return Knob
function Knob:setStyleSheet(value) end

--- Get the value property.
---@return integer
function Knob:getValue() end

--- Set the value property.
---@param value integer
---@return Knob
function Knob:setValue(value) end

--- Get the notchesVisible property.
---@return boolean
function Knob:getNotchesVisible() end

--- Set the notchesVisible property.
---@param value boolean
---@return Knob
function Knob:setNotchesVisible(value) end

--- Get the notchesVisible property.
---@return boolean
function Knob:isNotchesVisible() end

--- Attach a handler for onValueChanged.
---@param handler fun(widget: Knob)
---@return Knob
function Knob:setOnValueChanged(handler) end

---@class LCDNumber
local LCDNumber = {}

--- Get the enabled property.
---@return boolean
function LCDNumber:getEnabled() end

--- Set the enabled property.
---@param value boolean
---@return LCDNumber
function LCDNumber:setEnabled(value) end

--- Get the enabled property.
---@return boolean
function LCDNumber:isEnabled() end

--- Get the visible property.
---@return boolean
function LCDNumber:getVisible() end

--- Set the visible property.
---@param value boolean
---@return LCDNumber
function LCDNumber:setVisible(value) end

--- Get the visible property.
---@return boolean
function LCDNumber:isVisible() end

--- Get the toolTip property.
---@return string
function LCDNumber:getToolTip() end

--- Set the toolTip property.
---@param value string
---@return LCDNumber
function LCDNumber:setToolTip(value) end

--- Get the styleSheet property.
---@return string
function LCDNumber:getStyleSheet() end

--- Set the styleSheet property.
---@param value string
---@return LCDNumber
function LCDNumber:setStyleSheet(value) end

--- Get the digitCount property.
---@return integer
function LCDNumber:getDigitCount() end

--- Set the digitCount property.
---@param value integer
---@return LCDNumber
function LCDNumber:setDigitCount(value) end

--- Get the segmentStyle property.
---@return any
function LCDNumber:getSegmentStyle() end

--- Set the segmentStyle property.
---@param value any
---@return LCDNumber
function LCDNumber:setSegmentStyle(value) end

---@class Label
local Label = {}

--- Get the enabled property.
---@return boolean
function Label:getEnabled() end

--- Set the enabled property.
---@param value boolean
---@return Label
function Label:setEnabled(value) end

--- Get the enabled property.
---@return boolean
function Label:isEnabled() end

--- Get the visible property.
---@return boolean
function Label:getVisible() end

--- Set the visible property.
---@param value boolean
---@return Label
function Label:setVisible(value) end

--- Get the visible property.
---@return boolean
function Label:isVisible() end

--- Get the toolTip property.
---@return string
function Label:getToolTip() end

--- Set the toolTip property.
---@param value string
---@return Label
function Label:setToolTip(value) end

--- Get the styleSheet property.
---@return string
function Label:getStyleSheet() end

--- Set the styleSheet property.
---@param value string
---@return Label
function Label:setStyleSheet(value) end

--- Get the text property.
---@return string
function Label:getText() end

--- Set the text property.
---@param value string
---@return Label
function Label:setText(value) end

--- Get the wordWrap property.
---@return boolean
function Label:getWordWrap() end

--- Set the wordWrap property.
---@param value boolean
---@return Label
function Label:setWordWrap(value) end

--- Get the wordWrap property.
---@return boolean
function Label:isWordWrap() end

--- Get the textAlignment property.
---@return any
function Label:getTextAlignment() end

--- Set the textAlignment property.
---@param value any
---@return Label
function Label:setTextAlignment(value) end

---@class LineEdit
local LineEdit = {}

--- Get the enabled property.
---@return boolean
function LineEdit:getEnabled() end

--- Set the enabled property.
---@param value boolean
---@return LineEdit
function LineEdit:setEnabled(value) end

--- Get the enabled property.
---@return boolean
function LineEdit:isEnabled() end

--- Get the visible property.
---@return boolean
function LineEdit:getVisible() end

--- Set the visible property.
---@param value boolean
---@return LineEdit
function LineEdit:setVisible(value) end

--- Get the visible property.
---@return boolean
function LineEdit:isVisible() end

--- Get the toolTip property.
---@return string
function LineEdit:getToolTip() end

--- Set the toolTip property.
---@param value string
---@return LineEdit
function LineEdit:setToolTip(value) end

--- Get the styleSheet property.
---@return string
function LineEdit:getStyleSheet() end

--- Set the styleSheet property.
---@param value string
---@return LineEdit
function LineEdit:setStyleSheet(value) end

--- Get the text property.
---@return string
function LineEdit:getText() end

--- Set the text property.
---@param value string
---@return LineEdit
function LineEdit:setText(value) end

--- Get the readOnly property.
---@return boolean
function LineEdit:getReadOnly() end

--- Set the readOnly property.
---@param value boolean
---@return LineEdit
function LineEdit:setReadOnly(value) end

--- Get the readOnly property.
---@return boolean
function LineEdit:isReadOnly() end

--- Get the maxLength property.
---@return integer
function LineEdit:getMaxLength() end

--- Set the maxLength property.
---@param value integer
---@return LineEdit
function LineEdit:setMaxLength(value) end

--- Get placeholder shown while empty.
---@return string
function LineEdit:getHint() end

--- Set placeholder shown while empty.
---@param value string
---@return LineEdit
function LineEdit:setHint(value) end

--- Get one of: normal, password, hideinput, passwordonedit.
---@return any
function LineEdit:getInputMode() end

--- Set one of: normal, password, hideinput, passwordonedit.
---@param value any
---@return LineEdit
function LineEdit:setInputMode(value) end

--- Attach a handler for onTextChange.
---@param handler fun(widget: LineEdit)
---@return LineEdit
function LineEdit:setOnTextChange(handler) end

--- Attach a handler for onReturnPress.
---@param handler fun(widget: LineEdit)
---@return LineEdit
function LineEdit:setOnReturnPress(handler) end

--- Attach a handler for onTextSelection.
---@param handler fun(widget: LineEdit)
---@return LineEdit
function LineEdit:setOnTextSelection(handler) end

---@class ListBox
local ListBox = {}

--- Get the enabled property.
---@return boolean
function ListBox:getEnabled() end

--- Set the enabled property.
---@param value boolean
---@return ListBox
function ListBox:setEnabled(value) end

--- Get the enabled property.
---@return boolean
function ListBox:isEnabled() end

--- Get the visible property.
---@return boolean
function ListBox:getVisible() end

--- Set the visible property.
---@param value boolean
---@return ListBox
function ListBox:setVisible(value) end

--- Get the visible property.
---@return boolean
function ListBox:isVisible() end

--- Get the toolTip property.
---@return string
function ListBox:getToolTip() end

--- Set the toolTip property.
---@param value string
---@return ListBox
function ListBox:setToolTip(value) end

--- Get the styleSheet property.
---@return string
function ListBox:getStyleSheet() end

--- Set the styleSheet property.
---@param value string
---@return ListBox
function ListBox:setStyleSheet(value) end

--- Attach a handler for onItemSelect.
---@param handler fun(widget: ListBox)
---@return ListBox
function ListBox:setOnItemSelect(handler) end

--- Attach a handler for onItemDoubleClick.
---@param handler fun(widget: ListBox)
---@return ListBox
function ListBox:setOnItemDoubleClick(handler) end

---@class Menu
local Menu = {}

--- Get the enabled property.
---@return boolean
function Menu:getEnabled() end

--- Set the enabled property.
---@param value boolean
---@return Menu
function Menu:setEnabled(value) end

--- Get the enabled property.
---@return boolean
function Menu:isEnabled() end

--- Get the visible property.
---@return boolean
function Menu:getVisible() end

--- Set the visible property.
---@param value boolean
---@return Menu
function Menu:setVisible(value) end

--- Get the visible property.
---@return boolean
function Menu:isVisible() end

--- Get the toolTip property.
---@return string
function Menu:getToolTip() end

--- Set the toolTip property.
---@param value string
---@return Menu
function Menu:setToolTip(value) end

--- Get the styleSheet property.
---@return string
function Menu:getStyleSheet() end

--- Set the styleSheet property.
---@param value string
---@return Menu
function Menu:setStyleSheet(value) end

--- Get the title property.
---@return string
function Menu:getTitle() end

--- Set the title property.
---@param value string
---@return Menu
function Menu:setTitle(value) end

--- Get the icon property.
---@return any
function Menu:getIcon() end

--- Set the icon property.
---@param value any
---@return Menu
function Menu:setIcon(value) end

--- Attach a handler for onClick.
---@param handler fun(widget: Menu)
---@return Menu
function Menu:setOnClick(handler) end

---@class MenuItem
local MenuItem = {}

--- Get the action's caption.
---@return string
function MenuItem:getText() end

--- Set the action's caption.
---@param value string
---@return MenuItem
function MenuItem:setText(value) end

--- Get the icon property.
---@return any
function MenuItem:getIcon() end

--- Set the icon property.
---@param value any
---@return MenuItem
function MenuItem:setIcon(value) end

--- Get the enabled property.
---@return boolean
function MenuItem:getEnabled() end

--- Set the enabled property.
---@param value boolean
---@return MenuItem
function MenuItem:setEnabled(value) end

--- Get the enabled property.
---@return boolean
function MenuItem:isEnabled() end

--- Get the visible property.
---@return boolean
function MenuItem:getVisible() end

--- Set the visible property.
---@param value boolean
---@return MenuItem
function MenuItem:setVisible(value) end

--- Get the visible property.
---@return boolean
function MenuItem:isVisible() end

--- Get the checkable property.
---@return boolean
function MenuItem:getCheckable() end

--- Set the checkable property.
---@param value boolean
---@return MenuItem
function MenuItem:setCheckable(value) end

--- Get the checkable property.
---@return boolean
function MenuItem:isCheckable() end

--- Get the checked property.
---@return boolean
function MenuItem:getChecked() end

--- Set the checked property.
---@param value boolean
---@return MenuItem
function MenuItem:setChecked(value) end

--- Get the checked property.
---@return boolean
function MenuItem:isChecked() end

--- Get the separator property.
---@return boolean
function MenuItem:getSeparator() end

--- Set the separator property.
---@param value boolean
---@return MenuItem
function MenuItem:setSeparator(value) end

--- Get the separator property.
---@return boolean
function MenuItem:isSeparator() end

--- Get the toolTip property.
---@return string
function MenuItem:getToolTip() end

--- Set the toolTip property.
---@param value string
---@return MenuItem
function MenuItem:setToolTip(value) end

--- Get the statusTip property.
---@return string
function MenuItem:getStatusTip() end

--- Set the statusTip property.
---@param value string
---@return MenuItem
function MenuItem:setStatusTip(value) end

--- Get the shortcut property.
---@return string
function MenuItem:getShortcut() end

--- Set the shortcut property.
---@param value string
---@return MenuItem
function MenuItem:setShortcut(value) end

--- Attach a handler for onClick.
---@param handler fun(widget: MenuItem)
---@return MenuItem
function MenuItem:setOnClick(handler) end

---@class Menubar
local Menubar = {}

--- Get the enabled property.
---@return boolean
function Menubar:getEnabled() end

--- Set the enabled property.
---@param value boolean
---@return Menubar
function Menubar:setEnabled(value) end

--- Get the enabled property.
---@return boolean
function Menubar:isEnabled() end

--- Get the visible property.
---@return boolean
function Menubar:getVisible() end

--- Set the visible property.
---@param value boolean
---@return Menubar
function Menubar:setVisible(value) end

--- Get the visible property.
---@return boolean
function Menubar:isVisible() end

--- Get the toolTip property.
---@return string
function Menubar:getToolTip() end

--- Set the toolTip property.
---@param value string
---@return Menubar
function Menubar:setToolTip(value) end

--- Get the styleSheet property.
---@return string
function Menubar:getStyleSheet() end

--- Set the styleSheet property.
---@param value string
---@return Menubar
function Menubar:setStyleSheet(value) end

---@class Modal
local Modal = {}

--- Get the enabled property.
---@return boolean
function Modal:getEnabled() end

--- Set the enabled property.
---@param value boolean
---@return Modal
function Modal:setEnabled(value) end

--- Get the enabled property.
---@return boolean
function Modal:isEnabled() end

--- Get the visible property.
---@return boolean
function Modal:getVisible() end

--- Set the visible property.
---@param value boolean
---@return Modal
function Modal:setVisible(value) end

--- Get the visible property.
---@return boolean
function Modal:isVisible() end

--- Get the toolTip property.
---@return string
function Modal:getToolTip() end

--- Set the toolTip property.
---@param value string
---@return Modal
function Modal:setToolTip(value) end

--- Get the styleSheet property.
---@return string
function Modal:getStyleSheet() end

--- Set the styleSheet property.
---@param value string
---@return Modal
function Modal:setStyleSheet(value) end

--- Get the title property.
---@return string
function Modal:getTitle() end

--- Set the title property.
---@param value string
---@return Modal
function Modal:setTitle(value) end

--- Get the icon property.
---@return any
function Modal:getIcon() end

--- Set the icon property.
---@param value any
---@return Modal
function Modal:setIcon(value) end

--- Get the modal property.
---@return boolean
function Modal:getModal() end

--- Set the modal property.
---@param value boolean
---@return Modal
function Modal:setModal(value) end

--- Get the modal property.
---@return boolean
function Modal:isModal() end

--- Get the layout property.
---@return any
function Modal:getLayout() end

--- Set the layout property.
---@param value any
---@return Modal
function Modal:setLayout(value) end

---@class ProgressBar
local ProgressBar = {}

--- Get the enabled property.
---@return boolean
function ProgressBar:getEnabled() end

--- Set the enabled property.
---@param value boolean
---@return ProgressBar
function ProgressBar:setEnabled(value) end

--- Get the enabled property.
---@return boolean
function ProgressBar:isEnabled() end

--- Get the visible property.
---@return boolean
function ProgressBar:getVisible() end

--- Set the visible property.
---@param value boolean
---@return ProgressBar
function ProgressBar:setVisible(value) end

--- Get the visible property.
---@return boolean
function ProgressBar:isVisible() end

--- Get the toolTip property.
---@return string
function ProgressBar:getToolTip() end

--- Set the toolTip property.
---@param value string
---@return ProgressBar
function ProgressBar:setToolTip(value) end

--- Get the styleSheet property.
---@return string
function ProgressBar:getStyleSheet() end

--- Set the styleSheet property.
---@param value string
---@return ProgressBar
function ProgressBar:setStyleSheet(value) end

--- Get the value property.
---@return integer
function ProgressBar:getValue() end

--- Set the value property.
---@param value integer
---@return ProgressBar
function ProgressBar:setValue(value) end

--- Get the orientation property.
---@return any
function ProgressBar:getOrientation() end

--- Set the orientation property.
---@param value any
---@return ProgressBar
function ProgressBar:setOrientation(value) end

---@class RadioButton
local RadioButton = {}

--- Get the enabled property.
---@return boolean
function RadioButton:getEnabled() end

--- Set the enabled property.
---@param value boolean
---@return RadioButton
function RadioButton:setEnabled(value) end

--- Get the enabled property.
---@return boolean
function RadioButton:isEnabled() end

--- Get the visible property.
---@return boolean
function RadioButton:getVisible() end

--- Set the visible property.
---@param value boolean
---@return RadioButton
function RadioButton:setVisible(value) end

--- Get the visible property.
---@return boolean
function RadioButton:isVisible() end

--- Get the toolTip property.
---@return string
function RadioButton:getToolTip() end

--- Set the toolTip property.
---@param value string
---@return RadioButton
function RadioButton:setToolTip(value) end

--- Get the styleSheet property.
---@return string
function RadioButton:getStyleSheet() end

--- Set the styleSheet property.
---@param value string
---@return RadioButton
function RadioButton:setStyleSheet(value) end

--- Get the text property.
---@return string
function RadioButton:getText() end

--- Set the text property.
---@param value string
---@return RadioButton
function RadioButton:setText(value) end

--- Get the checked property.
---@return boolean
function RadioButton:getChecked() end

--- Set the checked property.
---@param value boolean
---@return RadioButton
function RadioButton:setChecked(value) end

--- Get the checked property.
---@return boolean
function RadioButton:isChecked() end

--- Get the icon property.
---@return any
function RadioButton:getIcon() end

--- Set the icon property.
---@param value any
---@return RadioButton
function RadioButton:setIcon(value) end

--- Get a {width, height} pair.
---@return any
function RadioButton:getIconSize() end

--- Set a {width, height} pair.
---@param value any
---@return RadioButton
function RadioButton:setIconSize(value) end

--- Attach a handler for onClick.
---@param handler fun(widget: RadioButton)
---@return RadioButton
function RadioButton:setOnClick(handler) end

---@class Scroller
local Scroller = {}

--- Get the enabled property.
---@return boolean
function Scroller:getEnabled() end

--- Set the enabled property.
---@param value boolean
---@return Scroller
function Scroller:setEnabled(value) end

--- Get the enabled property.
---@return boolean
function Scroller:isEnabled() end

--- Get the visible property.
---@return boolean
function Scroller:getVisible() end

--- Set the visible property.
---@param value boolean
---@return Scroller
function Scroller:setVisible(value) end

--- Get the visible property.
---@return boolean
function Scroller:isVisible() end

--- Get the toolTip property.
---@return string
function Scroller:getToolTip() end

--- Set the toolTip property.
---@param value string
---@return Scroller
function Scroller:setToolTip(value) end

--- Get the styleSheet property.
---@return string
function Scroller:getStyleSheet() end

--- Set the styleSheet property.
---@param value string
---@return Scroller
function Scroller:setStyleSheet(value) end

--- Get the resizable property.
---@return boolean
function Scroller:getResizable() end

--- Set the resizable property.
---@param value boolean
---@return Scroller
function Scroller:setResizable(value) end

--- Get the resizable property.
---@return boolean
function Scroller:isResizable() end

---@class Separator
local Separator = {}

--- Get the enabled property.
---@return boolean
function Separator:getEnabled() end

--- Set the enabled property.
---@param value boolean
---@return Separator
function Separator:setEnabled(value) end

--- Get the enabled property.
---@return boolean
function Separator:isEnabled() end

--- Get the visible property.
---@return boolean
function Separator:getVisible() end

--- Set the visible property.
---@param value boolean
---@return Separator
function Separator:setVisible(value) end

--- Get the visible property.
---@return boolean
function Separator:isVisible() end

--- Get the toolTip property.
---@return string
function Separator:getToolTip() end

--- Set the toolTip property.
---@param value string
---@return Separator
function Separator:setToolTip(value) end

--- Get the styleSheet property.
---@return string
function Separator:getStyleSheet() end

--- Set the styleSheet property.
---@param value string
---@return Separator
function Separator:setStyleSheet(value) end

---@class Slider
local Slider = {}

--- Get the enabled property.
---@return boolean
function Slider:getEnabled() end

--- Set the enabled property.
---@param value boolean
---@return Slider
function Slider:setEnabled(value) end

--- Get the enabled property.
---@return boolean
function Slider:isEnabled() end

--- Get the visible property.
---@return boolean
function Slider:getVisible() end

--- Set the visible property.
---@param value boolean
---@return Slider
function Slider:setVisible(value) end

--- Get the visible property.
---@return boolean
function Slider:isVisible() end

--- Get the toolTip property.
---@return string
function Slider:getToolTip() end

--- Set the toolTip property.
---@param value string
---@return Slider
function Slider:setToolTip(value) end

--- Get the styleSheet property.
---@return string
function Slider:getStyleSheet() end

--- Set the styleSheet property.
---@param value string
---@return Slider
function Slider:setStyleSheet(value) end

--- Get the value property.
---@return integer
function Slider:getValue() end

--- Set the value property.
---@param value integer
---@return Slider
function Slider:setValue(value) end

--- Get the orientation property.
---@return any
function Slider:getOrientation() end

--- Set the orientation property.
---@param value any
---@return Slider
function Slider:setOrientation(value) end

--- Get the tickPosition property.
---@return any
function Slider:getTickPosition() end

--- Set the tickPosition property.
---@param value any
---@return Slider
function Slider:setTickPosition(value) end

--- Attach a handler for onValueChange.
---@param handler fun(widget: Slider)
---@return Slider
function Slider:setOnValueChange(handler) end

---@class SlidingStackedWidget
local SlidingStackedWidget = {}

--- Get the enabled property.
---@return boolean
function SlidingStackedWidget:getEnabled() end

--- Set the enabled property.
---@param value boolean
---@return SlidingStackedWidget
function SlidingStackedWidget:setEnabled(value) end

--- Get the enabled property.
---@return boolean
function SlidingStackedWidget:isEnabled() end

--- Get the visible property.
---@return boolean
function SlidingStackedWidget:getVisible() end

--- Set the visible property.
---@param value boolean
---@return SlidingStackedWidget
function SlidingStackedWidget:setVisible(value) end

--- Get the visible property.
---@return boolean
function SlidingStackedWidget:isVisible() end

--- Get the toolTip property.
---@return string
function SlidingStackedWidget:getToolTip() end

--- Set the toolTip property.
---@param value string
---@return SlidingStackedWidget
function SlidingStackedWidget:setToolTip(value) end

--- Get the styleSheet property.
---@return string
function SlidingStackedWidget:getStyleSheet() end

--- Set the styleSheet property.
---@param value string
---@return SlidingStackedWidget
function SlidingStackedWidget:setStyleSheet(value) end

---@class Spacer
local Spacer = {}

---@class Spinner
local Spinner = {}

--- Get the enabled property.
---@return boolean
function Spinner:getEnabled() end

--- Set the enabled property.
---@param value boolean
---@return Spinner
function Spinner:setEnabled(value) end

--- Get the enabled property.
---@return boolean
function Spinner:isEnabled() end

--- Get the visible property.
---@return boolean
function Spinner:getVisible() end

--- Set the visible property.
---@param value boolean
---@return Spinner
function Spinner:setVisible(value) end

--- Get the visible property.
---@return boolean
function Spinner:isVisible() end

--- Get the toolTip property.
---@return string
function Spinner:getToolTip() end

--- Set the toolTip property.
---@param value string
---@return Spinner
function Spinner:setToolTip(value) end

--- Get the styleSheet property.
---@return string
function Spinner:getStyleSheet() end

--- Set the styleSheet property.
---@param value string
---@return Spinner
function Spinner:setStyleSheet(value) end

--- Get the value property.
---@return integer
function Spinner:getValue() end

--- Set the value property.
---@param value integer
---@return Spinner
function Spinner:setValue(value) end

--- Get the prefix property.
---@return string
function Spinner:getPrefix() end

--- Set the prefix property.
---@param value string
---@return Spinner
function Spinner:setPrefix(value) end

--- Get the suffix property.
---@return string
function Spinner:getSuffix() end

--- Set the suffix property.
---@param value string
---@return Spinner
function Spinner:setSuffix(value) end

--- Attach a handler for onValueChange.
---@param handler fun(widget: Spinner)
---@return Spinner
function Spinner:setOnValueChange(handler) end

---@class Splitter
local Splitter = {}

--- Get the enabled property.
---@return boolean
function Splitter:getEnabled() end

--- Set the enabled property.
---@param value boolean
---@return Splitter
function Splitter:setEnabled(value) end

--- Get the enabled property.
---@return boolean
function Splitter:isEnabled() end

--- Get the visible property.
---@return boolean
function Splitter:getVisible() end

--- Set the visible property.
---@param value boolean
---@return Splitter
function Splitter:setVisible(value) end

--- Get the visible property.
---@return boolean
function Splitter:isVisible() end

--- Get the toolTip property.
---@return string
function Splitter:getToolTip() end

--- Set the toolTip property.
---@param value string
---@return Splitter
function Splitter:setToolTip(value) end

--- Get the styleSheet property.
---@return string
function Splitter:getStyleSheet() end

--- Set the styleSheet property.
---@param value string
---@return Splitter
function Splitter:setStyleSheet(value) end

--- Get the handleWidth property.
---@return integer
function Splitter:getHandleWidth() end

--- Set the handleWidth property.
---@param value integer
---@return Splitter
function Splitter:setHandleWidth(value) end

--- Get the orientation property.
---@return any
function Splitter:getOrientation() end

--- Set the orientation property.
---@param value any
---@return Splitter
function Splitter:setOrientation(value) end

--- Get a list of pane sizes, one per child.
---@return any
function Splitter:getSizes() end

--- Set a list of pane sizes, one per child.
---@param value any
---@return Splitter
function Splitter:setSizes(value) end

---@class StackedLayout
local StackedLayout = {}

--- Get the spacing property.
---@return integer
function StackedLayout:getSpacing() end

--- Set the spacing property.
---@param value integer
---@return StackedLayout
function StackedLayout:setSpacing(value) end

---@class StatusBar
local StatusBar = {}

--- Get the enabled property.
---@return boolean
function StatusBar:getEnabled() end

--- Set the enabled property.
---@param value boolean
---@return StatusBar
function StatusBar:setEnabled(value) end

--- Get the enabled property.
---@return boolean
function StatusBar:isEnabled() end

--- Get the visible property.
---@return boolean
function StatusBar:getVisible() end

--- Set the visible property.
---@param value boolean
---@return StatusBar
function StatusBar:setVisible(value) end

--- Get the visible property.
---@return boolean
function StatusBar:isVisible() end

--- Get the toolTip property.
---@return string
function StatusBar:getToolTip() end

--- Set the toolTip property.
---@param value string
---@return StatusBar
function StatusBar:setToolTip(value) end

--- Get the styleSheet property.
---@return string
function StatusBar:getStyleSheet() end

--- Set the styleSheet property.
---@param value string
---@return StatusBar
function StatusBar:setStyleSheet(value) end

--- Get the sizeGripEnabled property.
---@return boolean
function StatusBar:getSizeGripEnabled() end

--- Set the sizeGripEnabled property.
---@param value boolean
---@return StatusBar
function StatusBar:setSizeGripEnabled(value) end

--- Get the sizeGripEnabled property.
---@return boolean
function StatusBar:isSizeGripEnabled() end

---@class SysNotification
local SysNotification = {}

--- Get the notification's icon.
---@return any
function SysNotification:getIcon() end

--- Set the notification's icon.
---@param value any
---@return SysNotification
function SysNotification:setIcon(value) end

--- Fired when the user clicks the notification balloon.
---@param handler fun(widget: SysNotification)
---@return SysNotification
function SysNotification:setOnClick(handler) end

---@class SysTray
local SysTray = {}

--- Get the tray icon's image.
---@return any
function SysTray:getIcon() end

--- Set the tray icon's image.
---@param value any
---@return SysTray
function SysTray:setIcon(value) end

--- Get the toolTip property.
---@return string
function SysTray:getToolTip() end

--- Set the toolTip property.
---@param value string
---@return SysTray
function SysTray:setToolTip(value) end

--- Get the visible property.
---@return boolean
function SysTray:getVisible() end

--- Set the visible property.
---@param value boolean
---@return SysTray
function SysTray:setVisible(value) end

--- Get the visible property.
---@return boolean
function SysTray:isVisible() end

--- Get the tray icon's right-click context menu.
---@return any
function SysTray:getMenu() end

--- Set the tray icon's right-click context menu.
---@param value any
---@return SysTray
function SysTray:setMenu(value) end

--- Fired when the user clicks or double-clicks the tray icon.
---@param handler fun(widget: SysTray)
---@return SysTray
function SysTray:setOnActivated(handler) end

---@class Tab
local Tab = {}

--- Get the enabled property.
---@return boolean
function Tab:getEnabled() end

--- Set the enabled property.
---@param value boolean
---@return Tab
function Tab:setEnabled(value) end

--- Get the enabled property.
---@return boolean
function Tab:isEnabled() end

--- Get the visible property.
---@return boolean
function Tab:getVisible() end

--- Set the visible property.
---@param value boolean
---@return Tab
function Tab:setVisible(value) end

--- Get the visible property.
---@return boolean
function Tab:isVisible() end

--- Get the toolTip property.
---@return string
function Tab:getToolTip() end

--- Set the toolTip property.
---@param value string
---@return Tab
function Tab:setToolTip(value) end

--- Get the styleSheet property.
---@return string
function Tab:getStyleSheet() end

--- Set the styleSheet property.
---@param value string
---@return Tab
function Tab:setStyleSheet(value) end

--- Get the movable property.
---@return boolean
function Tab:getMovable() end

--- Set the movable property.
---@param value boolean
---@return Tab
function Tab:setMovable(value) end

--- Get the movable property.
---@return boolean
function Tab:isMovable() end

--- Get the tabsClosable property.
---@return boolean
function Tab:getTabsClosable() end

--- Set the tabsClosable property.
---@param value boolean
---@return Tab
function Tab:setTabsClosable(value) end

--- Get the tabsClosable property.
---@return boolean
function Tab:isTabsClosable() end

--- Get the tabPosition property.
---@return any
function Tab:getTabPosition() end

--- Set the tabPosition property.
---@param value any
---@return Tab
function Tab:setTabPosition(value) end

---@class TabItem
local TabItem = {}

--- Get the enabled property.
---@return boolean
function TabItem:getEnabled() end

--- Set the enabled property.
---@param value boolean
---@return TabItem
function TabItem:setEnabled(value) end

--- Get the enabled property.
---@return boolean
function TabItem:isEnabled() end

--- Get the visible property.
---@return boolean
function TabItem:getVisible() end

--- Set the visible property.
---@param value boolean
---@return TabItem
function TabItem:setVisible(value) end

--- Get the visible property.
---@return boolean
function TabItem:isVisible() end

--- Get the toolTip property.
---@return string
function TabItem:getToolTip() end

--- Set the toolTip property.
---@param value string
---@return TabItem
function TabItem:setToolTip(value) end

--- Get the styleSheet property.
---@return string
function TabItem:getStyleSheet() end

--- Set the styleSheet property.
---@param value string
---@return TabItem
function TabItem:setStyleSheet(value) end

--- Get the layout property.
---@return any
function TabItem:getLayout() end

--- Set the layout property.
---@param value any
---@return TabItem
function TabItem:setLayout(value) end

---@class Table
local Table = {}

--- Get the enabled property.
---@return boolean
function Table:getEnabled() end

--- Set the enabled property.
---@param value boolean
---@return Table
function Table:setEnabled(value) end

--- Get the enabled property.
---@return boolean
function Table:isEnabled() end

--- Get the visible property.
---@return boolean
function Table:getVisible() end

--- Set the visible property.
---@param value boolean
---@return Table
function Table:setVisible(value) end

--- Get the visible property.
---@return boolean
function Table:isVisible() end

--- Get the toolTip property.
---@return string
function Table:getToolTip() end

--- Set the toolTip property.
---@param value string
---@return Table
function Table:setToolTip(value) end

--- Get the styleSheet property.
---@return string
function Table:getStyleSheet() end

--- Set the styleSheet property.
---@param value string
---@return Table
function Table:setStyleSheet(value) end

--- Get the showGrid property.
---@return boolean
function Table:getShowGrid() end

--- Set the showGrid property.
---@param value boolean
---@return Table
function Table:setShowGrid(value) end

--- Get the showGrid property.
---@return boolean
function Table:isShowGrid() end

--- Get the sortingEnabled property.
---@return boolean
function Table:getSortingEnabled() end

--- Set the sortingEnabled property.
---@param value boolean
---@return Table
function Table:setSortingEnabled(value) end

--- Get the sortingEnabled property.
---@return boolean
function Table:isSortingEnabled() end

--- Get the alternatingRowColors property.
---@return boolean
function Table:getAlternatingRowColors() end

--- Set the alternatingRowColors property.
---@param value boolean
---@return Table
function Table:setAlternatingRowColors(value) end

--- Get the alternatingRowColors property.
---@return boolean
function Table:isAlternatingRowColors() end

--- Attach a handler for onCellClick.
---@param handler fun(widget: Table)
---@return Table
function Table:setOnCellClick(handler) end

--- Attach a handler for onCellDoubleClick.
---@param handler fun(widget: Table)
---@return Table
function Table:setOnCellDoubleClick(handler) end

--- Attach a handler for onCellChange.
---@param handler fun(widget: Table)
---@return Table
function Table:setOnCellChange(handler) end

---@class TableItem
local TableItem = {}

--- Get the text property.
---@return string
function TableItem:getText() end

--- Set the text property.
---@param value string
---@return TableItem
function TableItem:setText(value) end

---@class TextField
local TextField = {}

--- Get the enabled property.
---@return boolean
function TextField:getEnabled() end

--- Set the enabled property.
---@param value boolean
---@return TextField
function TextField:setEnabled(value) end

--- Get the enabled property.
---@return boolean
function TextField:isEnabled() end

--- Get the visible property.
---@return boolean
function TextField:getVisible() end

--- Set the visible property.
---@param value boolean
---@return TextField
function TextField:setVisible(value) end

--- Get the visible property.
---@return boolean
function TextField:isVisible() end

--- Get the toolTip property.
---@return string
function TextField:getToolTip() end

--- Set the toolTip property.
---@param value string
---@return TextField
function TextField:setToolTip(value) end

--- Get the styleSheet property.
---@return string
function TextField:getStyleSheet() end

--- Set the styleSheet property.
---@param value string
---@return TextField
function TextField:setStyleSheet(value) end

--- Get the editor's plain-text content.
---@return string
function TextField:getPlainText() end

--- Set the editor's plain-text content.
---@param value string
---@return TextField
function TextField:setPlainText(value) end

--- Get the html property.
---@return string
function TextField:getHtml() end

--- Set the html property.
---@param value string
---@return TextField
function TextField:setHtml(value) end

--- Get the readOnly property.
---@return boolean
function TextField:getReadOnly() end

--- Set the readOnly property.
---@param value boolean
---@return TextField
function TextField:setReadOnly(value) end

--- Get the readOnly property.
---@return boolean
function TextField:isReadOnly() end

--- Get placeholder shown while empty.
---@return string
function TextField:getHint() end

--- Set placeholder shown while empty.
---@param value string
---@return TextField
function TextField:setHint(value) end

--- Attach a handler for onTextChange.
---@param handler fun(widget: TextField)
---@return TextField
function TextField:setOnTextChange(handler) end

--- Attach a handler for onCursorMove.
---@param handler fun(widget: TextField)
---@return TextField
function TextField:setOnCursorMove(handler) end

---@class Theme
local Theme = {}

---@class TimePicker
local TimePicker = {}

--- Get the enabled property.
---@return boolean
function TimePicker:getEnabled() end

--- Set the enabled property.
---@param value boolean
---@return TimePicker
function TimePicker:setEnabled(value) end

--- Get the enabled property.
---@return boolean
function TimePicker:isEnabled() end

--- Get the visible property.
---@return boolean
function TimePicker:getVisible() end

--- Set the visible property.
---@param value boolean
---@return TimePicker
function TimePicker:setVisible(value) end

--- Get the visible property.
---@return boolean
function TimePicker:isVisible() end

--- Get the toolTip property.
---@return string
function TimePicker:getToolTip() end

--- Set the toolTip property.
---@param value string
---@return TimePicker
function TimePicker:setToolTip(value) end

--- Get the styleSheet property.
---@return string
function TimePicker:getStyleSheet() end

--- Set the styleSheet property.
---@param value string
---@return TimePicker
function TimePicker:setStyleSheet(value) end

---@class Toolbar
local Toolbar = {}

--- Get the enabled property.
---@return boolean
function Toolbar:getEnabled() end

--- Set the enabled property.
---@param value boolean
---@return Toolbar
function Toolbar:setEnabled(value) end

--- Get the enabled property.
---@return boolean
function Toolbar:isEnabled() end

--- Get the visible property.
---@return boolean
function Toolbar:getVisible() end

--- Set the visible property.
---@param value boolean
---@return Toolbar
function Toolbar:setVisible(value) end

--- Get the visible property.
---@return boolean
function Toolbar:isVisible() end

--- Get the toolTip property.
---@return string
function Toolbar:getToolTip() end

--- Set the toolTip property.
---@param value string
---@return Toolbar
function Toolbar:setToolTip(value) end

--- Get the styleSheet property.
---@return string
function Toolbar:getStyleSheet() end

--- Set the styleSheet property.
---@param value string
---@return Toolbar
function Toolbar:setStyleSheet(value) end

--- Get the movable property.
---@return boolean
function Toolbar:getMovable() end

--- Set the movable property.
---@param value boolean
---@return Toolbar
function Toolbar:setMovable(value) end

--- Get the movable property.
---@return boolean
function Toolbar:isMovable() end

--- Get the floatable property.
---@return boolean
function Toolbar:getFloatable() end

--- Set the floatable property.
---@param value boolean
---@return Toolbar
function Toolbar:setFloatable(value) end

--- Get the floatable property.
---@return boolean
function Toolbar:isFloatable() end

--- Get the iconSize property.
---@return any
function Toolbar:getIconSize() end

--- Set the iconSize property.
---@param value any
---@return Toolbar
function Toolbar:setIconSize(value) end

--- Get how buttons show icon/text: icononly, textonly, textbesideicon, textundericon, followstyle.
---@return any
function Toolbar:getToolButtonStyle() end

--- Set how buttons show icon/text: icononly, textonly, textbesideicon, textundericon, followstyle.
---@param value any
---@return Toolbar
function Toolbar:setToolButtonStyle(value) end

---@class ToolbarButton
local ToolbarButton = {}

--- Get the action's caption.
---@return string
function ToolbarButton:getText() end

--- Set the action's caption.
---@param value string
---@return ToolbarButton
function ToolbarButton:setText(value) end

--- Get the icon property.
---@return any
function ToolbarButton:getIcon() end

--- Set the icon property.
---@param value any
---@return ToolbarButton
function ToolbarButton:setIcon(value) end

--- Get the enabled property.
---@return boolean
function ToolbarButton:getEnabled() end

--- Set the enabled property.
---@param value boolean
---@return ToolbarButton
function ToolbarButton:setEnabled(value) end

--- Get the enabled property.
---@return boolean
function ToolbarButton:isEnabled() end

--- Get the visible property.
---@return boolean
function ToolbarButton:getVisible() end

--- Set the visible property.
---@param value boolean
---@return ToolbarButton
function ToolbarButton:setVisible(value) end

--- Get the visible property.
---@return boolean
function ToolbarButton:isVisible() end

--- Get the checkable property.
---@return boolean
function ToolbarButton:getCheckable() end

--- Set the checkable property.
---@param value boolean
---@return ToolbarButton
function ToolbarButton:setCheckable(value) end

--- Get the checkable property.
---@return boolean
function ToolbarButton:isCheckable() end

--- Get the checked property.
---@return boolean
function ToolbarButton:getChecked() end

--- Set the checked property.
---@param value boolean
---@return ToolbarButton
function ToolbarButton:setChecked(value) end

--- Get the checked property.
---@return boolean
function ToolbarButton:isChecked() end

--- Get the separator property.
---@return boolean
function ToolbarButton:getSeparator() end

--- Set the separator property.
---@param value boolean
---@return ToolbarButton
function ToolbarButton:setSeparator(value) end

--- Get the separator property.
---@return boolean
function ToolbarButton:isSeparator() end

--- Get the toolTip property.
---@return string
function ToolbarButton:getToolTip() end

--- Set the toolTip property.
---@param value string
---@return ToolbarButton
function ToolbarButton:setToolTip(value) end

--- Get the statusTip property.
---@return string
function ToolbarButton:getStatusTip() end

--- Set the statusTip property.
---@param value string
---@return ToolbarButton
function ToolbarButton:setStatusTip(value) end

--- Get the shortcut property.
---@return string
function ToolbarButton:getShortcut() end

--- Set the shortcut property.
---@param value string
---@return ToolbarButton
function ToolbarButton:setShortcut(value) end

--- Attach a handler for onClick.
---@param handler fun(widget: ToolbarButton)
---@return ToolbarButton
function ToolbarButton:setOnClick(handler) end

---@class TreeView
local TreeView = {}

--- Get the enabled property.
---@return boolean
function TreeView:getEnabled() end

--- Set the enabled property.
---@param value boolean
---@return TreeView
function TreeView:setEnabled(value) end

--- Get the enabled property.
---@return boolean
function TreeView:isEnabled() end

--- Get the visible property.
---@return boolean
function TreeView:getVisible() end

--- Set the visible property.
---@param value boolean
---@return TreeView
function TreeView:setVisible(value) end

--- Get the visible property.
---@return boolean
function TreeView:isVisible() end

--- Get the toolTip property.
---@return string
function TreeView:getToolTip() end

--- Set the toolTip property.
---@param value string
---@return TreeView
function TreeView:setToolTip(value) end

--- Get the styleSheet property.
---@return string
function TreeView:getStyleSheet() end

--- Set the styleSheet property.
---@param value string
---@return TreeView
function TreeView:setStyleSheet(value) end

--- Get the headerHidden property.
---@return boolean
function TreeView:getHeaderHidden() end

--- Set the headerHidden property.
---@param value boolean
---@return TreeView
function TreeView:setHeaderHidden(value) end

--- Get the headerHidden property.
---@return boolean
function TreeView:isHeaderHidden() end

--- Attach a handler for onItemClick.
---@param handler fun(widget: TreeView)
---@return TreeView
function TreeView:setOnItemClick(handler) end

--- Attach a handler for onItemDoubleClick.
---@param handler fun(widget: TreeView)
---@return TreeView
function TreeView:setOnItemDoubleClick(handler) end

---@class TreeViewItem
local TreeViewItem = {}

--- Get the expanded property.
---@return boolean
function TreeViewItem:getExpanded() end

--- Set the expanded property.
---@param value boolean
---@return TreeViewItem
function TreeViewItem:setExpanded(value) end

--- Get the expanded property.
---@return boolean
function TreeViewItem:isExpanded() end

---@class TreeWidget
local TreeWidget = {}

--- Get the enabled property.
---@return boolean
function TreeWidget:getEnabled() end

--- Set the enabled property.
---@param value boolean
---@return TreeWidget
function TreeWidget:setEnabled(value) end

--- Get the enabled property.
---@return boolean
function TreeWidget:isEnabled() end

--- Get the visible property.
---@return boolean
function TreeWidget:getVisible() end

--- Set the visible property.
---@param value boolean
---@return TreeWidget
function TreeWidget:setVisible(value) end

--- Get the visible property.
---@return boolean
function TreeWidget:isVisible() end

--- Get the toolTip property.
---@return string
function TreeWidget:getToolTip() end

--- Set the toolTip property.
---@param value string
---@return TreeWidget
function TreeWidget:setToolTip(value) end

--- Get the styleSheet property.
---@return string
function TreeWidget:getStyleSheet() end

--- Set the styleSheet property.
---@param value string
---@return TreeWidget
function TreeWidget:setStyleSheet(value) end

--- Get the headerHidden property.
---@return boolean
function TreeWidget:getHeaderHidden() end

--- Set the headerHidden property.
---@param value boolean
---@return TreeWidget
function TreeWidget:setHeaderHidden(value) end

--- Get the headerHidden property.
---@return boolean
function TreeWidget:isHeaderHidden() end

--- Attach a handler for onItemClick.
---@param handler fun(widget: TreeWidget)
---@return TreeWidget
function TreeWidget:setOnItemClick(handler) end

--- Attach a handler for onItemDoubleClick.
---@param handler fun(widget: TreeWidget)
---@return TreeWidget
function TreeWidget:setOnItemDoubleClick(handler) end

---@class VLayout
local VLayout = {}

--- Get the spacing property.
---@return integer
function VLayout:getSpacing() end

--- Set the spacing property.
---@param value integer
---@return VLayout
function VLayout:setSpacing(value) end

---@class VLine
local VLine = {}

--- Get the enabled property.
---@return boolean
function VLine:getEnabled() end

--- Set the enabled property.
---@param value boolean
---@return VLine
function VLine:setEnabled(value) end

--- Get the enabled property.
---@return boolean
function VLine:isEnabled() end

--- Get the visible property.
---@return boolean
function VLine:getVisible() end

--- Set the visible property.
---@param value boolean
---@return VLine
function VLine:setVisible(value) end

--- Get the visible property.
---@return boolean
function VLine:isVisible() end

--- Get the toolTip property.
---@return string
function VLine:getToolTip() end

--- Set the toolTip property.
---@param value string
---@return VLine
function VLine:setToolTip(value) end

--- Get the styleSheet property.
---@return string
function VLine:getStyleSheet() end

--- Set the styleSheet property.
---@param value string
---@return VLine
function VLine:setStyleSheet(value) end

---@class Window
local Window = {}

--- Get the enabled property.
---@return boolean
function Window:getEnabled() end

--- Set the enabled property.
---@param value boolean
---@return Window
function Window:setEnabled(value) end

--- Get the enabled property.
---@return boolean
function Window:isEnabled() end

--- Get the visible property.
---@return boolean
function Window:getVisible() end

--- Set the visible property.
---@param value boolean
---@return Window
function Window:setVisible(value) end

--- Get the visible property.
---@return boolean
function Window:isVisible() end

--- Get the toolTip property.
---@return string
function Window:getToolTip() end

--- Set the toolTip property.
---@param value string
---@return Window
function Window:setToolTip(value) end

--- Get the styleSheet property.
---@return string
function Window:getStyleSheet() end

--- Set the styleSheet property.
---@param value string
---@return Window
function Window:setStyleSheet(value) end

--- Get the window's title-bar text.
---@return string
function Window:getTitle() end

--- Set the window's title-bar text.
---@param value string
---@return Window
function Window:setTitle(value) end

--- Get the window's icon.
---@return any
function Window:getIcon() end

--- Set the window's icon.
---@param value any
---@return Window
function Window:setIcon(value) end

local ui = {}
ui.Accordion = Accordion
ui.AdvancedSlider = AdvancedSlider
ui.AutoComplete = AutoComplete
ui.Button = Button
ui.ButtonGroup = ButtonGroup
ui.Calendar = Calendar
ui.CheckBox = CheckBox
ui.ComboBox = ComboBox
ui.CommandButton = CommandButton
ui.Container = Container
ui.DatePicker = DatePicker
ui.Dialogs = Dialogs
ui.Dock = Dock
ui.Dockable = Dockable
ui.DoubleSpinner = DoubleSpinner
ui.DropMenu = DropMenu
ui.DropShadow = DropShadow
ui.FontComboBox = FontComboBox
ui.FormLayout = FormLayout
ui.GifPlayer = GifPlayer
ui.GridLayout = GridLayout
ui.GroupBox = GroupBox
ui.HLayout = HLayout
ui.HLine = HLine
ui.Image = Image
ui.KeyboardShortcut = KeyboardShortcut
ui.Knob = Knob
ui.LCDNumber = LCDNumber
ui.Label = Label
ui.LineEdit = LineEdit
ui.ListBox = ListBox
ui.Menu = Menu
ui.MenuItem = MenuItem
ui.Menubar = Menubar
ui.Modal = Modal
ui.ProgressBar = ProgressBar
ui.RadioButton = RadioButton
ui.Scroller = Scroller
ui.Separator = Separator
ui.Slider = Slider
ui.SlidingStackedWidget = SlidingStackedWidget
ui.Spacer = Spacer
ui.Spinner = Spinner
ui.Splitter = Splitter
ui.StackedLayout = StackedLayout
ui.StatusBar = StatusBar
ui.SysNotification = SysNotification
ui.SysTray = SysTray
ui.Tab = Tab
ui.TabItem = TabItem
ui.Table = Table
ui.TableItem = TableItem
ui.TextField = TextField
ui.Theme = Theme
ui.TimePicker = TimePicker
ui.Toolbar = Toolbar
ui.ToolbarButton = ToolbarButton
ui.TreeView = TreeView
ui.TreeViewItem = TreeViewItem
ui.TreeWidget = TreeWidget
ui.VLayout = VLayout
ui.VLine = VLine
ui.Window = Window
return ui
