---@meta
-- GENERATED by tools/generate_stubs.py - do not edit by hand.

---@class Button
local Button = {}

--- Get the enabled property.
---@return boolean
function Button:getEnabled() end

--- Set the enabled property.
---@param value boolean
---@return Button
function Button:setEnabled(value) end

--- Get the enabled property.
---@return boolean
function Button:isEnabled() end

--- Get the visible property.
---@return boolean
function Button:getVisible() end

--- Set the visible property.
---@param value boolean
---@return Button
function Button:setVisible(value) end

--- Get the visible property.
---@return boolean
function Button:isVisible() end

--- Get the toolTip property.
---@return string
function Button:getToolTip() end

--- Set the toolTip property.
---@param value string
---@return Button
function Button:setToolTip(value) end

--- Get the styleSheet property.
---@return string
function Button:getStyleSheet() end

--- Set the styleSheet property.
---@param value string
---@return Button
function Button:setStyleSheet(value) end

--- Get the button's caption.
---@return string
function Button:getText() end

--- Set the button's caption.
---@param value string
---@return Button
function Button:setText(value) end

--- Get the icon property.
---@return any
function Button:getIcon() end

--- Set the icon property.
---@param value any
---@return Button
function Button:setIcon(value) end

--- Get the flat property.
---@return boolean
function Button:getFlat() end

--- Set the flat property.
---@param value boolean
---@return Button
function Button:setFlat(value) end

--- Get the flat property.
---@return boolean
function Button:isFlat() end

--- Get the checkable property.
---@return boolean
function Button:getCheckable() end

--- Set the checkable property.
---@param value boolean
---@return Button
function Button:setCheckable(value) end

--- Get the checkable property.
---@return boolean
function Button:isCheckable() end

--- Get the checked property.
---@return boolean
function Button:getChecked() end

--- Set the checked property.
---@param value boolean
---@return Button
function Button:setChecked(value) end

--- Get the checked property.
---@return boolean
function Button:isChecked() end

--- Fired when clicked.
---@param handler fun(widget: Button)
---@return Button
function Button:setOnClick(handler) end

---@class CheckBox
local CheckBox = {}

--- Get the enabled property.
---@return boolean
function CheckBox:getEnabled() end

--- Set the enabled property.
---@param value boolean
---@return CheckBox
function CheckBox:setEnabled(value) end

--- Get the enabled property.
---@return boolean
function CheckBox:isEnabled() end

--- Get the visible property.
---@return boolean
function CheckBox:getVisible() end

--- Set the visible property.
---@param value boolean
---@return CheckBox
function CheckBox:setVisible(value) end

--- Get the visible property.
---@return boolean
function CheckBox:isVisible() end

--- Get the toolTip property.
---@return string
function CheckBox:getToolTip() end

--- Set the toolTip property.
---@param value string
---@return CheckBox
function CheckBox:setToolTip(value) end

--- Get the styleSheet property.
---@return string
function CheckBox:getStyleSheet() end

--- Set the styleSheet property.
---@param value string
---@return CheckBox
function CheckBox:setStyleSheet(value) end

--- Get the text property.
---@return string
function CheckBox:getText() end

--- Set the text property.
---@param value string
---@return CheckBox
function CheckBox:setText(value) end

--- Get the checked property.
---@return boolean
function CheckBox:getChecked() end

--- Set the checked property.
---@param value boolean
---@return CheckBox
function CheckBox:setChecked(value) end

--- Get the checked property.
---@return boolean
function CheckBox:isChecked() end

--- Attach a handler for onCheck.
---@param handler fun(widget: CheckBox)
---@return CheckBox
function CheckBox:setOnCheck(handler) end

---@class ComboBox
local ComboBox = {}

--- Get the enabled property.
---@return boolean
function ComboBox:getEnabled() end

--- Set the enabled property.
---@param value boolean
---@return ComboBox
function ComboBox:setEnabled(value) end

--- Get the enabled property.
---@return boolean
function ComboBox:isEnabled() end

--- Get the visible property.
---@return boolean
function ComboBox:getVisible() end

--- Set the visible property.
---@param value boolean
---@return ComboBox
function ComboBox:setVisible(value) end

--- Get the visible property.
---@return boolean
function ComboBox:isVisible() end

--- Get the toolTip property.
---@return string
function ComboBox:getToolTip() end

--- Set the toolTip property.
---@param value string
---@return ComboBox
function ComboBox:setToolTip(value) end

--- Get the styleSheet property.
---@return string
function ComboBox:getStyleSheet() end

--- Set the styleSheet property.
---@param value string
---@return ComboBox
function ComboBox:setStyleSheet(value) end

--- Get the editable property.
---@return boolean
function ComboBox:getEditable() end

--- Set the editable property.
---@param value boolean
---@return ComboBox
function ComboBox:setEditable(value) end

--- Get the editable property.
---@return boolean
function ComboBox:isEditable() end

--- Attach a handler for onItemSelect.
---@param handler fun(widget: ComboBox)
---@return ComboBox
function ComboBox:setOnItemSelect(handler) end

---@class Label
local Label = {}

--- Get the enabled property.
---@return boolean
function Label:getEnabled() end

--- Set the enabled property.
---@param value boolean
---@return Label
function Label:setEnabled(value) end

--- Get the enabled property.
---@return boolean
function Label:isEnabled() end

--- Get the visible property.
---@return boolean
function Label:getVisible() end

--- Set the visible property.
---@param value boolean
---@return Label
function Label:setVisible(value) end

--- Get the visible property.
---@return boolean
function Label:isVisible() end

--- Get the toolTip property.
---@return string
function Label:getToolTip() end

--- Set the toolTip property.
---@param value string
---@return Label
function Label:setToolTip(value) end

--- Get the styleSheet property.
---@return string
function Label:getStyleSheet() end

--- Set the styleSheet property.
---@param value string
---@return Label
function Label:setStyleSheet(value) end

--- Get the text property.
---@return string
function Label:getText() end

--- Set the text property.
---@param value string
---@return Label
function Label:setText(value) end

--- Get the wordWrap property.
---@return boolean
function Label:getWordWrap() end

--- Set the wordWrap property.
---@param value boolean
---@return Label
function Label:setWordWrap(value) end

--- Get the wordWrap property.
---@return boolean
function Label:isWordWrap() end

--- Get the textAlignment property.
---@return any
function Label:getTextAlignment() end

--- Set the textAlignment property.
---@param value any
---@return Label
function Label:setTextAlignment(value) end

---@class ListBox
local ListBox = {}

--- Get the enabled property.
---@return boolean
function ListBox:getEnabled() end

--- Set the enabled property.
---@param value boolean
---@return ListBox
function ListBox:setEnabled(value) end

--- Get the enabled property.
---@return boolean
function ListBox:isEnabled() end

--- Get the visible property.
---@return boolean
function ListBox:getVisible() end

--- Set the visible property.
---@param value boolean
---@return ListBox
function ListBox:setVisible(value) end

--- Get the visible property.
---@return boolean
function ListBox:isVisible() end

--- Get the toolTip property.
---@return string
function ListBox:getToolTip() end

--- Set the toolTip property.
---@param value string
---@return ListBox
function ListBox:setToolTip(value) end

--- Get the styleSheet property.
---@return string
function ListBox:getStyleSheet() end

--- Set the styleSheet property.
---@param value string
---@return ListBox
function ListBox:setStyleSheet(value) end

--- Attach a handler for onItemSelect.
---@param handler fun(widget: ListBox)
---@return ListBox
function ListBox:setOnItemSelect(handler) end

--- Attach a handler for onItemDoubleClick.
---@param handler fun(widget: ListBox)
---@return ListBox
function ListBox:setOnItemDoubleClick(handler) end

local ui = {}
ui.Button = Button
ui.CheckBox = CheckBox
ui.ComboBox = ComboBox
ui.Label = Label
ui.ListBox = ListBox
return ui
