"""Explicit import list for every class exposed to Lua.

GENERATED by tools/generate_manifest.py - do not edit by hand.

Development and frozen builds both import from this list, so a class that is
missing here is missing in BOTH, rather than only in the packaged app.
"""

import importlib

MODULES = (
    "limekit.charts.areachart",
    "limekit.charts.barchart",
    "limekit.charts.barset",
    "limekit.charts.categoryaxis",
    "limekit.charts.chart",
    "limekit.charts.chartview",
    "limekit.charts.linechart",
    "limekit.charts.valueaxis",
    "limekit.layouts.formlayout",
    "limekit.layouts.grid",
    "limekit.layouts.hlayout",
    "limekit.layouts.stackedlayout",
    "limekit.layouts.vlayout",
    "limekit.services.autocomplete",
    "limekit.services.concurrency",
    "limekit.services.database",
    "limekit.services.dialogs",
    "limekit.services.dropshadow",
    "limekit.services.fs",
    "limekit.services.resources",
    "limekit.services.sysnotification",
    "limekit.services.system",
    "limekit.services.systray",
    "limekit.services.theming",
    "limekit.services.timer",
    "limekit.toolkit.text",
    "limekit.widgets.accordion",
    "limekit.widgets.advancedslider",
    "limekit.widgets.button",
    "limekit.widgets.buttongroup",
    "limekit.widgets.calendar",
    "limekit.widgets.checkbox",
    "limekit.widgets.combobox",
    "limekit.widgets.commandbutton",
    "limekit.widgets.container",
    "limekit.widgets.datepicker",
    "limekit.widgets.dock",
    "limekit.widgets.doublespinner",
    "limekit.widgets.fontcombobox",
    "limekit.widgets.gifplayer",
    "limekit.widgets.groupbox",
    "limekit.widgets.horizontal_line",
    "limekit.widgets.image",
    "limekit.widgets.knob",
    "limekit.widgets.label",
    "limekit.widgets.lcdnumber",
    "limekit.widgets.lineedit",
    "limekit.widgets.listbox",
    "limekit.widgets.menu",
    "limekit.widgets.modal",
    "limekit.widgets.progressbar",
    "limekit.widgets.radiobutton",
    "limekit.widgets.scroller",
    "limekit.widgets.separator",
    "limekit.widgets.slider",
    "limekit.widgets.slidingstackedwidget",
    "limekit.widgets.spacer",
    "limekit.widgets.spinner",
    "limekit.widgets.splitter",
    "limekit.widgets.statusbar",
    "limekit.widgets.tab",
    "limekit.widgets.table",
    "limekit.widgets.textfield",
    "limekit.widgets.timepicker",
    "limekit.widgets.toolbar",
    "limekit.widgets.treeview",
    "limekit.widgets.vertical_line",
    "limekit.widgets.window",
)


def import_all():
    """Import every module so their __lime__ declarations register."""
    for name in MODULES:
        importlib.import_module(name)
