"""Explicit import list for every class exposed to Lua.

GENERATED by tools/generate_manifest.py - do not edit by hand.

Development and frozen builds both import from this list, so a class that is
missing here is missing in BOTH, rather than only in the packaged app.
"""

import importlib

MODULES = (
    "limekit.layouts.formlayout",
    "limekit.layouts.grid",
    "limekit.layouts.hlayout",
    "limekit.layouts.vlayout",
    "limekit.services.dialogs",
    "limekit.services.fs",
    "limekit.services.resources",
    "limekit.services.system",
    "limekit.services.theming",
    "limekit.toolkit.text",
    "limekit.widgets.button",
    "limekit.widgets.buttongroup",
    "limekit.widgets.checkbox",
    "limekit.widgets.combobox",
    "limekit.widgets.container",
    "limekit.widgets.dock",
    "limekit.widgets.doublespinner",
    "limekit.widgets.groupbox",
    "limekit.widgets.horizontal_line",
    "limekit.widgets.image",
    "limekit.widgets.label",
    "limekit.widgets.lineedit",
    "limekit.widgets.listbox",
    "limekit.widgets.menu",
    "limekit.widgets.modal",
    "limekit.widgets.progressbar",
    "limekit.widgets.radiobutton",
    "limekit.widgets.scroller",
    "limekit.widgets.slider",
    "limekit.widgets.spinner",
    "limekit.widgets.splitter",
    "limekit.widgets.statusbar",
    "limekit.widgets.tab",
    "limekit.widgets.table",
    "limekit.widgets.textfield",
    "limekit.widgets.toolbar",
    "limekit.widgets.treeview",
    "limekit.widgets.vertical_line",
    "limekit.widgets.window",
)


def import_all():
    """Import every module so their __lime__ declarations register."""
    for name in MODULES:
        importlib.import_module(name)
