"""Explicit import list for every class exposed to Lua.

GENERATED by tools/generate_manifest.py - do not edit by hand.

Development and frozen builds both import from this list, so a class that is
missing here is missing in BOTH, rather than only in the packaged app.
"""

import importlib

MODULES = (
    "limekit.layouts.grid",
    "limekit.layouts.hlayout",
    "limekit.layouts.vlayout",
    "limekit.services.dialogs",
    "limekit.services.fs",
    "limekit.services.resources",
    "limekit.services.system",
    "limekit.services.theming",
    "limekit.toolkit.text",
    "limekit.widgets.button",
    "limekit.widgets.checkbox",
    "limekit.widgets.combobox",
    "limekit.widgets.label",
    "limekit.widgets.listbox",
    "limekit.widgets.textfield",
    "limekit.widgets.window",
)


def import_all():
    """Import every module so their __lime__ declarations register."""
    for name in MODULES:
        importlib.import_module(name)
