-- GENERATED by tools/generate_lua.py - do not edit by hand.
--
-- This is a manifest, not live code: it lists every module/class that
-- `require("limekit.<module>")` resolves to via package.preload (see
-- kernel/bridge/runtime.py:install_modules), so nothing here is consumed
-- yet -- P1 wires this file into the loading path. Require the module you
-- need rather than relying on globals:
--
--     local ui = require("limekit.ui")
--     local win = ui.Window { title = "Hello" }

local limekit = {}

-- chart
limekit.chart = require("limekit.chart")
--   chart.AreaChart
--   chart.BarChart
--   chart.BarSet
--   chart.CategoryAxis
--   chart.Chart
--   chart.ChartCanvas
--   chart.ChartView
--   chart.LineChart
--   chart.ValueAxis

-- db
limekit.db = require("limekit.db")
--   db.Sqlite3

-- fs
limekit.fs = require("limekit.fs")
--   fs.FileSystem

-- res
limekit.res = require("limekit.res")
--   res.Resources

-- sys
limekit.sys = require("limekit.sys")
--   sys.Expr
--   sys.Signal
--   sys.System
--   sys.Thread
--   sys.Timer

-- ui
limekit.ui = require("limekit.ui")
--   ui.Accordion
--   ui.AdvancedSlider
--   ui.AutoComplete
--   ui.Button
--   ui.ButtonGroup
--   ui.Calendar
--   ui.CheckBox
--   ui.ComboBox
--   ui.CommandButton
--   ui.Container
--   ui.DatePicker
--   ui.Dialogs
--   ui.Dock
--   ui.Dockable
--   ui.DoubleSpinner
--   ui.DropMenu
--   ui.DropShadow
--   ui.FontComboBox
--   ui.FormLayout
--   ui.GifPlayer
--   ui.GridLayout
--   ui.GroupBox
--   ui.HLayout
--   ui.HLine
--   ui.Image
--   ui.Knob
--   ui.LCDNumber
--   ui.Label
--   ui.LineEdit
--   ui.ListBox
--   ui.Menu
--   ui.MenuItem
--   ui.Menubar
--   ui.Modal
--   ui.ProgressBar
--   ui.RadioButton
--   ui.Scroller
--   ui.Separator
--   ui.Slider
--   ui.SlidingStackedWidget
--   ui.Spacer
--   ui.Spinner
--   ui.Splitter
--   ui.StackedLayout
--   ui.StatusBar
--   ui.SysNotification
--   ui.SysTray
--   ui.Tab
--   ui.TabItem
--   ui.Table
--   ui.TableItem
--   ui.TextField
--   ui.Theme
--   ui.TimePicker
--   ui.Toolbar
--   ui.ToolbarButton
--   ui.TreeView
--   ui.TreeViewItem
--   ui.VLayout
--   ui.VLine
--   ui.Window


return limekit
