-- GENERATED by tools/generate_lua.py - do not edit by hand.
--
-- This is a manifest, not live code: it lists every module/class that
-- `require("limekit.<module>")` resolves to via package.preload (see
-- kernel/bridge/runtime.py:install_modules), so nothing here is consumed
-- yet -- P1 wires this file into the loading path. Require the module you
-- need rather than relying on globals:
--
--     local ui = require("limekit.ui")
--     local win = ui.Window { title = "Hello" }

local limekit = {}

-- fs
limekit.fs = require("limekit.fs")
--   fs.FileSystem

-- res
limekit.res = require("limekit.res")
--   res.Resources

-- sys
limekit.sys = require("limekit.sys")
--   sys.Expr
--   sys.System

-- ui
limekit.ui = require("limekit.ui")
--   ui.Button
--   ui.CheckBox
--   ui.ComboBox
--   ui.Dialogs
--   ui.GridLayout
--   ui.HLayout
--   ui.Label
--   ui.ListBox
--   ui.TextField
--   ui.Theme
--   ui.VLayout
--   ui.Window


return limekit
