-- GENERATED by tools/generate_lua.py - do not edit by hand.
--
-- Every class carrying a __lime__ path is reachable here. Require the module
-- you need rather than relying on globals:
--
--     local ui = require("limekit.ui")
--     local win = ui.Window { title = "Hello" }

local limekit = {}

-- ui
limekit.ui = require("limekit.ui")
--   ui.Button
--   ui.CheckBox
--   ui.ComboBox
--   ui.Label
--   ui.ListBox


return limekit
