"""Emit Lua Language Server stubs so Lua users get autocomplete.

    python tools/generate_stubs.py
"""

import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO))

from limekit.kernel import manifest                      # noqa: E402
from limekit.kernel.registry import registry              # noqa: E402

LUA_TYPES = {
    str: "string", int: "integer", float: "number", bool: "boolean",
}


def lua_type(python_type):
    return LUA_TYPES.get(python_type, "any")


def render_class(name, cls):
    lines = [f"---@class {name}"]
    lines.append(f"local {name} = {{}}")
    lines.append("")

    for prop in cls.__props__:
        getter, setter, alias = prop.accessor_names()

        # Only document accessors that were actually installed. A Prop whose
        # Qt method is absent from the MRO (an abstract mixin not yet
        # combined with a concrete widget) is silently skipped by
        # declarative._install_prop -- documenting it here would describe a
        # method that doesn't exist at runtime.
        if not hasattr(cls, getter) or not hasattr(cls, setter):
            continue

        typename = lua_type(prop.type)
        doc = prop.doc or f"the {prop.name} property"

        lines.append(f"--- Get {doc}.")
        lines.append(f"---@return {typename}")
        lines.append(f"function {name}:{getter}() end")
        lines.append("")

        lines.append(f"--- Set {doc}.")
        lines.append(f"---@param value {typename}")
        lines.append(f"---@return {name}")
        lines.append(f"function {name}:{setter}(value) end")
        lines.append("")

        if alias:
            lines.append(f"--- Get {doc}.")
            lines.append("---@return boolean")
            lines.append(f"function {name}:{alias}() end")
            lines.append("")

    for event in cls.__events__:
        doc = event.doc or f"Attach a handler for {event.name}."
        lines.append(f"--- {doc}")
        lines.append(f"---@param handler fun(widget: {name})")
        lines.append(f"---@return {name}")
        lines.append(f"function {name}:{event.setter_name()}(handler) end")
        lines.append("")

    return "\n".join(lines)


def render_module(module, members):
    lines = [
        "---@meta",
        "-- GENERATED by tools/generate_stubs.py - do not edit by hand.",
        "",
    ]
    for name, cls in sorted(members.items()):
        lines.append(render_class(name, cls))
    lines.append(f"local {module} = {{}}")
    for name in sorted(members):
        lines.append(f"{module}.{name} = {name}")
    lines.append(f"return {module}")
    lines.append("")
    return "\n".join(lines)


def main():
    manifest.import_all()
    target = REPO / "limekit" / "runtime" / "lua" / "stubs"
    target.mkdir(parents=True, exist_ok=True)

    for module, members in registry.modules().items():
        path = target / f"{module}.lua"
        path.write_text(render_module(module, members), encoding="utf-8", newline="\n")
        print(f"wrote {path}")


if __name__ == "__main__":
    main()
