"""Emit limekit/kernel/manifest.py from the classes that declare __lime__.

Run after adding or removing any exported class:

    python tools/generate_manifest.py
"""

import argparse
import ast
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
PACKAGE = REPO / "limekit"
SKIP = {"kernel", "build", "__pycache__"}

HEADER = '''"""Explicit import list for every class exposed to Lua.

GENERATED by tools/generate_manifest.py - do not edit by hand.

Development and frozen builds both import from this list, so a class that is
missing here is missing in BOTH, rather than only in the packaged app.
"""

import importlib

MODULES = (
'''

FOOTER = ''')


def import_all():
    """Import every module so their __lime__ declarations register."""
    for name in MODULES:
        importlib.import_module(name)
'''


def declares_lime(path):
    """True if the file assigns __lime__ at class scope."""
    try:
        tree = ast.parse(path.read_text(encoding="utf-8"))
    except (SyntaxError, UnicodeDecodeError):
        return False
    for node in ast.walk(tree):
        if not isinstance(node, ast.ClassDef):
            continue
        for stmt in node.body:
            targets = (
                stmt.targets if isinstance(stmt, ast.Assign)
                else [stmt.target] if isinstance(stmt, ast.AnnAssign)
                else []
            )
            for target in targets:
                if isinstance(target, ast.Name) and target.id == "__lime__":
                    return True
    return False


def discover(package_root=PACKAGE):
    modules = []
    for path in sorted(package_root.rglob("*.py")):
        if set(path.relative_to(package_root).parts) & SKIP:
            continue
        if path.name == "__init__.py":
            continue
        if declares_lime(path):
            rel = path.relative_to(package_root.parent).with_suffix("")
            modules.append(".".join(rel.parts))
    return tuple(modules)


def render(modules):
    body = "".join(f'    "{name}",\n' for name in modules)
    return HEADER + body + FOOTER


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--stdout", action="store_true",
                        help="print instead of writing the file")
    args = parser.parse_args()

    text = render(discover())
    if args.stdout:
        sys.stdout.write(text)
    else:
        target = PACKAGE / "kernel" / "manifest.py"
        target.write_text(text, encoding="utf-8", newline="\n")
        print(f"wrote {target}")


if __name__ == "__main__":
    main()
