"""Emit limekit/runtime/lua/limekit.lua from the registry.

The generated file is comments-only scaffolding for now -- a manifest of
what `require("limekit.<module>")` will resolve to. Nothing consumes it
yet; P1 wires it into the actual module loading path. It replaces the
hand-maintained app table only in the sense that this is where that
responsibility will eventually live, not that anything reads this file
today.

    python tools/generate_lua.py
"""

import argparse
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO))

from limekit.kernel import manifest                      # noqa: E402
from limekit.kernel.registry import registry              # noqa: E402

HEADER = """-- GENERATED by tools/generate_lua.py - do not edit by hand.
--
-- This is a manifest, not live code: it lists every module/class that
-- `require("limekit.<module>")` resolves to via package.preload (see
-- kernel/bridge/runtime.py:install_modules), so nothing here is consumed
-- yet -- P1 wires this file into the loading path. Require the module you
-- need rather than relying on globals:
--
--     local ui = require("limekit.ui")
--     local win = ui.Window { title = "Hello" }

local limekit = {}

"""

FOOTER = """
return limekit
"""


def render():
    manifest.import_all()
    lines = [HEADER]
    for module, members in sorted(registry.modules().items()):
        lines.append(f'-- {module}\n')
        lines.append(f'limekit.{module} = require("limekit.{module}")\n')
        for name in sorted(members):
            lines.append(f'--   {module}.{name}\n')
        lines.append("\n")
    lines.append(FOOTER)
    return "".join(lines)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--stdout", action="store_true")
    args = parser.parse_args()

    text = render()
    if args.stdout:
        sys.stdout.write(text)
    else:
        target = REPO / "limekit" / "runtime" / "lua" / "limekit.lua"
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(text, encoding="utf-8", newline="\n")
        print(f"wrote {target}")


if __name__ == "__main__":
    main()
